import type { OrgType } from "@/types/erp";

export interface Module {
  id: string;
  name: string;
  label: string;
  icon: string;
  path: string;
  enabled: boolean;
  orgTypes: OrgType[];
  order: number;
  children?: Module[];
}

/**
 * Standard ERP modules configuration
 */
export const STANDARD_MODULES: Module[] = [
  {
    id: "dashboard",
    name: "dashboard",
    label: "Dashboard",
    icon: "LayoutDashboard",
    path: "/dashboard",
    enabled: true,
    orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
    order: 0,
  },
  {
    id: "inventory",
    name: "inventory",
    label: "Inventory",
    icon: "Package",
    path: "/inventory",
    enabled: true,
    orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
    order: 1,
    children: [
      {
        id: "inventory-products",
        name: "products",
        label: "Products",
        icon: "Box",
        path: "/inventory/products",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 0,
      },
      {
        id: "inventory-stock-levels",
        name: "stock-levels",
        label: "Stock Levels",
        icon: "Warehouse",
        path: "/inventory/stock-levels",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 1,
      },
      {
        id: "inventory-movements",
        name: "movements",
        label: "Stock Movements",
        icon: "ArrowLeftRight",
        path: "/inventory/movements",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 2,
      },
      {
        id: "inventory-receipts",
        name: "receipts",
        label: "Receipts (GRN)",
        icon: "PackageCheck",
        path: "/inventory/receipts",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 3,
      },
      {
        id: "inventory-receiving",
        name: "receiving",
        label: "Receiving Queue",
        icon: "ClipboardCheck",
        path: "/inventory/receiving",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 4,
      },
      {
        id: "inventory-costing",
        name: "costing",
        label: "Costing",
        icon: "Calculator",
        path: "/inventory/costing",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 5,
      },
      {
        id: "inventory-stock-explorer",
        name: "stock-explorer",
        label: "Stock Explorer",
        icon: "Search",
        path: "/inventory/stock-explorer",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 6,
      },
      {
        id: "inventory-valuation",
        name: "valuation",
        label: "Valuation",
        icon: "Scale",
        path: "/inventory/valuation",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 7,
      },
      {
        id: "inventory-transfers",
        name: "transfers",
        label: "Transfers",
        icon: "Truck",
        path: "/warehouse/transfers",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 8,
      },
      {
        id: "inventory-stocktake",
        name: "stocktake",
        label: "Stocktake / Cycle Count",
        icon: "ClipboardList",
        path: "/warehouse/cycle-counts",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 9,
      },
      {
        id: "inventory-warehouses",
        name: "warehouses",
        label: "Warehouses & Locations",
        icon: "MapPin",
        path: "/inventory/warehouses",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 10,
      },
    ],
  },
  {
    id: "costing",
    name: "costing",
    label: "COSTING",
    icon: "Calculator",
    path: "/inventory/costing",
    enabled: true,
    orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
    order: 15,
    children: [
      {
        id: "costing-allocation",
        name: "costing-allocation",
        label: "Batch Allocation",
        icon: "Sparkles",
        path: "/inventory/costing",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 0,
      },
      {
        id: "costing-batch-report",
        name: "costing-batch-report",
        label: "Batch Cost Report",
        icon: "BarChart3",
        path: "/reports/batch-costing",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 1,
      },
      {
        id: "costing-pricing",
        name: "costing-pricing",
        label: "Pricing",
        icon: "Tag",
        path: "/pricing/overview",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 2,
      },
      {
        id: "costing-price-lists",
        name: "costing-price-lists",
        label: "Price Lists",
        icon: "List",
        path: "/pricing/price-lists",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 3,
      },
    ],
  },
  {
    id: "sales",
    name: "sales",
    label: "Sales",
    icon: "ShoppingCart",
    path: "/sales",
    enabled: true,
    orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
    order: 2,
    children: [
      {
        id: "sales-orders",
        name: "orders",
        label: "Orders",
        icon: "FileText",
        path: "/sales/orders",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 0,
      },
      {
        id: "sales-customers",
        name: "customers",
        label: "Customers",
        icon: "Users",
        path: "/sales/customers",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 1,
      },
      {
        id: "sales-invoices",
        name: "invoices",
        label: "Invoices",
        icon: "Receipt",
        path: "/sales/invoices",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 2,
      },
      {
        id: "sales-deliveries",
        name: "deliveries",
        label: "Deliveries",
        icon: "Truck",
        path: "/sales/deliveries",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 3,
      },
    ],
  },
  {
    id: "purchasing",
    name: "purchasing",
    label: "Purchasing",
    icon: "ShoppingBag",
    path: "/purchasing",
    enabled: true,
    orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
    order: 3,
    children: [
      {
        id: "purchasing-requests",
        name: "requests",
        label: "Purchase Requests",
        icon: "ClipboardList",
        path: "/purchasing/requests",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 0,
      },
      {
        id: "purchasing-orders",
        name: "orders",
        label: "Purchase Orders",
        icon: "FileText",
        path: "/purchasing/orders",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 1,
      },
      {
        id: "purchasing-guided-sourcing-flow",
        name: "guided-sourcing-flow",
        label: "Guided Sourcing Flow",
        icon: "Workflow",
        path: "/purchasing/sourcing-flow",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 2,
      },
      {
        id: "purchasing-grn",
        name: "grn",
        label: "Goods Receipt (GRN)",
        icon: "PackageCheck",
        path: "/inventory/receipts",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 3,
      },
      {
        id: "purchasing-suppliers",
        name: "suppliers",
        label: "Suppliers",
        icon: "Building2",
        path: "/ap/suppliers",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 4,
      },
      {
        id: "purchasing-supplier-invoices",
        name: "supplier-invoices",
        label: "Supplier Invoices (AP)",
        icon: "Receipt",
        path: "/ap/bills",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 5,
      },
      {
        id: "purchasing-returns",
        name: "returns",
        label: "Purchase Returns / Debit Notes",
        icon: "RotateCcw",
        path: "/purchasing/purchase-returns",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 6,
      },
      {
        id: "purchasing-cash-weight-audit",
        name: "cash-weight-audit",
        label: "Cash-to-Weight Audit",
        icon: "Scale",
        path: "/purchasing/cash-weight-audit",
        enabled: true,
        orgTypes: ["DISTRIBUTOR"],
        order: 7,
      },
    ],
  },
  {
    id: "manufacturing",
    name: "manufacturing",
    label: "Manufacturing",
    icon: "Factory",
    path: "/manufacturing",
    enabled: true,
    orgTypes: ["MANUFACTURER"],
    order: 4,
    children: [
      {
        id: "manufacturing-bom",
        name: "bom",
        label: "Bills of Material",
        icon: "List",
        path: "/manufacturing/bom",
        enabled: true,
        orgTypes: ["MANUFACTURER"],
        order: 0,
      },
      {
        id: "manufacturing-work-orders",
        name: "work-orders",
        label: "Work Orders",
        icon: "ClipboardList",
        path: "/manufacturing/work-orders",
        enabled: true,
        orgTypes: ["MANUFACTURER"],
        order: 1,
      },
      {
        id: "manufacturing-production",
        name: "production",
        label: "Production Runs",
        icon: "Cog",
        path: "/manufacturing/work-orders",
        enabled: true,
        orgTypes: ["MANUFACTURER"],
        order: 2,
      },
    ],
  },
  {
    id: "finance",
    name: "finance",
    label: "Finance",
    icon: "DollarSign",
    path: "/finance",
    enabled: true,
    orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
    order: 5,
    children: [
      {
        id: "finance-ledger",
        name: "ledger",
        label: "General Ledger",
        icon: "BookOpen",
        path: "/finance/ledger",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 0,
      },
      {
        id: "finance-payments",
        name: "payments",
        label: "Payments",
        icon: "CreditCard",
        path: "/finance/payments",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 1,
      },
      {
        id: "finance-reports",
        name: "reports",
        label: "Reports",
        icon: "BarChart3",
        path: "/finance/reports",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 2,
      },
    ],
  },
  {
    id: "settings",
    name: "settings",
    label: "Settings",
    icon: "Settings",
    path: "/settings",
    enabled: true,
    orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
    order: 99,
    children: [
      {
        id: "settings-org",
        name: "organization",
        label: "Organization",
        icon: "Building",
        path: "/settings/organization",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 0,
      },
      {
        id: "settings-users",
        name: "users",
        label: "Users & Roles",
        icon: "Users",
        path: "/settings/users",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 1,
      },
      {
        id: "settings-customization",
        name: "customization",
        label: "Customization",
        icon: "Sliders",
        path: "/settings/customization",
        enabled: true,
        orgTypes: ["MANUFACTURER", "DISTRIBUTOR", "SHOP"],
        order: 2,
      },
    ],
  },
];

export function getModulesForOrgType(orgType: OrgType): Module[] {
  return STANDARD_MODULES.filter(
    (module) => module.orgTypes.includes(orgType) && module.enabled
  ).map((module) => ({
    ...module,
    children: module.children?.filter(
      (child) => child.orgTypes.includes(orgType) && child.enabled
    ),
  }));
}

