import type { OrgType } from "@/types/erp";

export type NavItem = {
  id: string;
  label: string;
  href?: string;
  icon: string; // lucide icon key
  moduleId: string;
  orgTypes?: OrgType[];
  permission?: string;
  children?: NavItem[];
  badge?: { type: "count" | "text"; value: string };
};

export type NavSection = {
  id: string;
  label: string;
  moduleId: string;
  orgTypes?: OrgType[];
  items: NavItem[];
};

export const NAV_SECTIONS: NavSection[] = [
  {
    id: "core",
    label: "Core",
    moduleId: "dashboard",
    items: [
      {
        id: "dashboard",
        label: "Dashboard",
        href: "/dashboard",
        icon: "LayoutDashboard",
        moduleId: "dashboard",
      },
      {
        id: "approvals",
        label: "Approvals Inbox",
        href: "/approvals",
        icon: "CheckCircle2",
        moduleId: "automation",
        permission: "approvals.read",
      },
      {
        id: "tasks",
        label: "Tasks / Work Queue",
        href: "/tasks",
        icon: "CheckSquare",
        moduleId: "automation",
      },
    ],
  },
  {
    id: "inventory",
    label: "Inventory",
    moduleId: "inventory",
    items: [
      {
        id: "inventory-products",
        label: "Products",
        href: "/inventory/products",
        icon: "Package",
        moduleId: "inventory",
        permission: "inventory.read",
      },
      {
        id: "inventory-stock-levels",
        label: "Stock Levels",
        href: "/inventory/stock-levels",
        icon: "Warehouse",
        moduleId: "inventory",
        permission: "inventory.read",
      },
      {
        id: "inventory-movements",
        label: "Stock Movements",
        href: "/inventory/movements",
        icon: "ArrowLeftRight",
        moduleId: "inventory",
        permission: "inventory.read",
      },
      {
        id: "inventory-transfers",
        label: "Transfers",
        href: "/inventory/transfers",
        icon: "Truck",
        moduleId: "inventory",
        permission: "inventory.write",
      },
      {
        id: "inventory-stocktake",
        label: "Stocktake / Cycle Count",
        href: "/inventory/stocktake",
        icon: "ClipboardCheck",
        moduleId: "inventory",
        permission: "inventory.write",
      },
      {
        id: "inventory-warehouses",
        label: "Warehouses & Locations",
        href: "/inventory/warehouses",
        icon: "MapPin",
        moduleId: "inventory",
        permission: "inventory.read",
      },
    ],
  },
  {
    id: "sales",
    label: "Sales",
    moduleId: "sales",
    items: [
      {
        id: "sales-orders",
        label: "Orders",
        href: "/sales/orders",
        icon: "ShoppingCart",
        moduleId: "sales",
        permission: "sales.orders.read",
      },
      {
        id: "sales-customers",
        label: "Customers",
        href: "/sales/customers",
        icon: "Users",
        moduleId: "sales",
        permission: "sales.customers.read",
      },
      {
        id: "sales-invoices",
        label: "Invoices",
        href: "/sales/invoices",
        icon: "Receipt",
        moduleId: "sales",
        permission: "sales.invoices.read",
      },
      {
        id: "sales-deliveries",
        label: "Deliveries",
        href: "/sales/deliveries",
        icon: "Truck",
        moduleId: "sales",
        permission: "sales.deliveries.read",
      },
      {
        id: "sales-returns",
        label: "Returns / Credit Notes",
        href: "/sales/returns",
        icon: "RotateCcw",
        moduleId: "sales",
        permission: "sales.returns.read",
      },
    ],
  },
  {
    id: "purchasing",
    label: "Purchasing / Procurement",
    moduleId: "purchasing",
    items: [
      {
        id: "purchasing-orders",
        label: "Purchase Orders",
        href: "/purchasing/purchase-orders",
        icon: "FileText",
        moduleId: "purchasing",
        permission: "purchasing.orders.read",
      },
      {
        id: "purchasing-suppliers",
        label: "Suppliers",
        href: "/purchasing/suppliers",
        icon: "Building2",
        moduleId: "purchasing",
        permission: "purchasing.suppliers.read",
      },
      {
        id: "purchasing-grn",
        label: "Goods Receipt (GRN)",
        href: "/purchasing/goods-receipt",
        icon: "PackageCheck",
        moduleId: "purchasing",
        permission: "purchasing.grn.read",
      },
      {
        id: "purchasing-supplier-invoices",
        label: "Supplier Invoices (AP Bills)",
        href: "/purchasing/supplier-invoices",
        icon: "FileText",
        moduleId: "purchasing",
        permission: "purchasing.bills.read",
      },
      {
        id: "purchasing-returns",
        label: "Purchase Returns",
        href: "/purchasing/purchase-returns",
        icon: "RotateCcw",
        moduleId: "purchasing",
        permission: "purchasing.returns.read",
      },
    ],
  },
  {
    id: "finance",
    label: "Finance & Accounting",
    moduleId: "finance",
    items: [
      {
        id: "finance-dashboard",
        label: "Finance Dashboard",
        href: "/finance",
        icon: "TrendingUp",
        moduleId: "finance",
        permission: "finance.read",
      },
      {
        id: "finance-gl",
        label: "General Ledger",
        href: "/finance/gl",
        icon: "BookOpen",
        moduleId: "finance",
        permission: "finance.gl.read",
      },
      {
        id: "finance-chart-of-accounts",
        label: "Chart of Accounts",
        href: "/finance/chart-of-accounts",
        icon: "ListTree",
        moduleId: "finance",
        permission: "finance.accounts.read",
      },
      {
        id: "finance-journals",
        label: "Journal Entries",
        href: "/finance/journals",
        icon: "FileEdit",
        moduleId: "finance",
        permission: "finance.journals.read",
      },
      {
        id: "finance-ar",
        label: "Accounts Receivable (AR)",
        href: "/finance/ar",
        icon: "ArrowDownCircle",
        moduleId: "finance",
        permission: "finance.ar.read",
      },
      {
        id: "finance-ap",
        label: "Accounts Payable (AP)",
        href: "/finance/ap",
        icon: "ArrowUpCircle",
        moduleId: "finance",
        permission: "finance.ap.read",
      },
      {
        id: "finance-payments",
        label: "Payments & Receipts",
        href: "/finance/payments",
        icon: "CreditCard",
        moduleId: "finance",
        permission: "finance.payments.read",
      },
      {
        id: "finance-bank-recon",
        label: "Bank Reconciliation",
        href: "/finance/bank-recon",
        icon: "Wallet",
        moduleId: "finance",
        permission: "finance.bank.read",
      },
      {
        id: "finance-tax",
        label: "Tax / VAT",
        href: "/finance/tax",
        icon: "Receipt",
        moduleId: "finance",
        permission: "finance.tax.read",
      },
      {
        id: "finance-fixed-assets",
        label: "Fixed Assets",
        href: "/finance/fixed-assets",
        icon: "Building",
        moduleId: "finance",
        permission: "finance.assets.read",
      },
      {
        id: "finance-budgets",
        label: "Budgets",
        href: "/finance/budgets",
        icon: "Target",
        moduleId: "finance",
        permission: "finance.budgets.read",
      },
      {
        id: "finance-statements",
        label: "Financial Statements",
        href: "/finance/statements",
        icon: "BarChart3",
        moduleId: "finance",
        permission: "finance.statements.read",
        children: [
          {
            id: "finance-statements-pnl",
            label: "P&L",
            href: "/finance/statements/pnl",
            icon: "TrendingUp",
            moduleId: "finance",
            permission: "finance.statements.read",
          },
          {
            id: "finance-statements-balance-sheet",
            label: "Balance Sheet",
            href: "/finance/statements/balance-sheet",
            icon: "Scale",
            moduleId: "finance",
            permission: "finance.statements.read",
          },
          {
            id: "finance-statements-cash-flow",
            label: "Cash Flow",
            href: "/finance/statements/cash-flow",
            icon: "ArrowLeftRight",
            moduleId: "finance",
            permission: "finance.statements.read",
          },
        ],
      },
      {
        id: "finance-period-close",
        label: "Period Close",
        href: "/finance/period-close",
        icon: "Lock",
        moduleId: "finance",
        permission: "finance.close.write",
      },
      {
        id: "finance-audit",
        label: "Audit Log (Finance)",
        href: "/finance/audit",
        icon: "FileSearch",
        moduleId: "finance",
        permission: "finance.audit.read",
      },
    ],
  },
  {
    id: "manufacturing",
    label: "Manufacturing",
    moduleId: "manufacturing",
    orgTypes: ["MANUFACTURER"],
    items: [
      {
        id: "manufacturing-boms",
        label: "Bills of Material (BOM)",
        href: "/manufacturing/boms",
        icon: "List",
        moduleId: "manufacturing",
        permission: "manufacturing.bom.read",
      },
      {
        id: "manufacturing-work-orders",
        label: "Work Orders",
        href: "/manufacturing/work-orders",
        icon: "ClipboardList",
        moduleId: "manufacturing",
        permission: "manufacturing.workorders.read",
      },
      {
        id: "manufacturing-production-runs",
        label: "Production Runs",
        href: "/manufacturing/production-runs",
        icon: "Cog",
        moduleId: "manufacturing",
        permission: "manufacturing.production.read",
      },
      {
        id: "manufacturing-wip",
        label: "WIP Tracking",
        href: "/manufacturing/wip",
        icon: "Package",
        moduleId: "manufacturing",
        permission: "manufacturing.wip.read",
      },
      {
        id: "manufacturing-qc",
        label: "Quality Control",
        href: "/manufacturing/qc",
        icon: "CheckCircle",
        moduleId: "manufacturing",
        permission: "manufacturing.qc.read",
      },
      {
        id: "manufacturing-yield",
        label: "Yield & Variance",
        href: "/manufacturing/yield",
        icon: "BarChart",
        moduleId: "manufacturing",
        permission: "manufacturing.yield.read",
      },
    ],
  },
  {
    id: "crm",
    label: "CRM",
    moduleId: "crm",
    items: [
      {
        id: "crm-accounts",
        label: "Accounts / Parties",
        href: "/crm/accounts",
        icon: "Building2",
        moduleId: "crm",
        permission: "crm.accounts.read",
      },
      {
        id: "crm-activities",
        label: "Activities / Notes",
        href: "/crm/activities",
        icon: "StickyNote",
        moduleId: "crm",
        permission: "crm.activities.read",
      },
      {
        id: "crm-deals",
        label: "Deals / Opportunities",
        href: "/crm/deals",
        icon: "TrendingUp",
        moduleId: "crm",
        permission: "crm.deals.read",
      },
      {
        id: "crm-tickets",
        label: "Support / Tickets",
        href: "/crm/tickets",
        icon: "Ticket",
        moduleId: "crm",
        permission: "crm.tickets.read",
      },
    ],
  },
  {
    id: "reports",
    label: "Reports",
    moduleId: "reports",
    items: [
      {
        id: "reports-library",
        label: "Report Library",
        href: "/reports",
        icon: "FileText",
        moduleId: "reports",
        permission: "reports.read",
      },
      {
        id: "reports-saved",
        label: "Saved Views",
        href: "/reports/saved",
        icon: "Bookmark",
        moduleId: "reports",
        permission: "reports.read",
      },
      {
        id: "reports-scheduled",
        label: "Scheduled Reports",
        href: "/reports/scheduled",
        icon: "Clock",
        moduleId: "reports",
        permission: "reports.schedule.read",
      },
      {
        id: "reports-exports",
        label: "Exports",
        href: "/reports/exports",
        icon: "Download",
        moduleId: "reports",
        permission: "reports.export.read",
      },
    ],
  },
  {
    id: "automation",
    label: "Automation Center",
    moduleId: "automation",
    items: [
      {
        id: "automation-dashboard",
        label: "Automation Dashboard",
        href: "/automation",
        icon: "Zap",
        moduleId: "automation",
        permission: "automation.read",
      },
      {
        id: "automation-rules",
        label: "Rules Engine",
        href: "/automation/rules",
        icon: "Workflow",
        moduleId: "automation",
        permission: "automation.rules.read",
      },
      {
        id: "automation-alerts",
        label: "Alerts & Notifications",
        href: "/automation/alerts",
        icon: "Bell",
        moduleId: "automation",
        permission: "automation.alerts.read",
        badge: { type: "count", value: "3" },
      },
      {
        id: "automation-schedules",
        label: "Scheduled Jobs",
        href: "/automation/schedules",
        icon: "Calendar",
        moduleId: "automation",
        permission: "automation.schedules.read",
      },
      {
        id: "automation-workflows",
        label: "Approvals Workflows",
        href: "/automation/workflows",
        icon: "CheckCircle2",
        moduleId: "automation",
        permission: "automation.workflows.read",
      },
      {
        id: "automation-integrations",
        label: "Integrations",
        href: "/automation/integrations",
        icon: "Plug",
        moduleId: "automation",
        permission: "automation.integrations.read",
      },
      {
        id: "automation-ai-insights",
        label: "AI Insights",
        href: "/automation/ai-insights",
        icon: "Brain",
        moduleId: "automation",
        permission: "automation.ai.read",
        badge: { type: "text", value: "NEW" },
      },
    ],
  },
  {
    id: "settings",
    label: "Settings",
    moduleId: "settings",
    items: [
      {
        id: "settings-org",
        label: "Organization Profile",
        href: "/settings/org",
        icon: "Building",
        moduleId: "settings",
        permission: "settings.org.read",
      },
      {
        id: "settings-branches",
        label: "Branches",
        href: "/settings/branches",
        icon: "MapPin",
        moduleId: "settings",
        permission: "settings.branches.read",
      },
      {
        id: "settings-users-roles",
        label: "Users & Roles",
        href: "/settings/users-roles",
        icon: "Users",
        moduleId: "settings",
        permission: "settings.users.read",
      },
      {
        id: "settings-preferences",
        label: "Preferences",
        href: "/settings/preferences",
        icon: "Settings",
        moduleId: "settings",
        permission: "settings.preferences.read",
      },
      {
        id: "settings-sequences",
        label: "Numbering Sequences",
        href: "/settings/sequences",
        icon: "Hash",
        moduleId: "settings",
        permission: "settings.sequences.read",
      },
      {
        id: "settings-customizer",
        label: "Customizer (Enterprise)",
        href: "/settings/customizer",
        icon: "Sliders",
        moduleId: "settings",
        permission: "settings.customizer.read",
        children: [
          {
            id: "settings-customizer-modules",
            label: "Modules",
            href: "/settings/customizer/modules",
            icon: "Grid",
            moduleId: "settings",
            permission: "settings.customizer.read",
          },
          {
            id: "settings-customizer-fields",
            label: "Custom Fields",
            href: "/settings/customizer/fields",
            icon: "FileText",
            moduleId: "settings",
            permission: "settings.customizer.read",
          },
          {
            id: "settings-customizer-workflows",
            label: "Workflows",
            href: "/settings/customizer/workflows",
            icon: "Workflow",
            moduleId: "settings",
            permission: "settings.customizer.read",
          },
          {
            id: "settings-customizer-dashboards",
            label: "Dashboards",
            href: "/settings/customizer/dashboards",
            icon: "LayoutDashboard",
            moduleId: "settings",
            permission: "settings.customizer.read",
          },
        ],
      },
    ],
  },
];





