import type { NavSectionConfig } from "./types";

export const NAV_SECTIONS_CONFIG: NavSectionConfig[] = [
  {
    key: "core",
    label: "Core",
    moduleKey: "dashboard",
    tier: "primary",
    order: 0,
    items: [
      { key: "control-tower", label: "Control Tower", href: "/control-tower", icon: "Gauge", moduleKey: "dashboard" },
      {
        key: "supply-chain-journey",
        label: "Supply chain journey",
        href: "/operations/supply-chain",
        icon: "Route",
        moduleKey: "dashboard",
        requiresFlags: ["procurementAuditCashWeight", "vmiReplenishment", "commissionEngine"],
      },
      { key: "dashboard", label: "Dashboard", href: "/dashboard", icon: "LayoutDashboard", moduleKey: "dashboard" },
      { key: "approvals", label: "Approvals", href: "/approvals", icon: "CheckCircle2", moduleKey: "automation", requiresFlags: ["approvals"], requiresPermissions: ["approvals.read"], children: [
        { key: "approvals-inbox", label: "Inbox", href: "/approvals/inbox", icon: "Inbox", moduleKey: "automation", requiresPermissions: ["approvals.read"] },
        { key: "approvals-requests", label: "My requests", href: "/approvals/requests", icon: "Send", moduleKey: "automation", requiresPermissions: ["approvals.read"] },
      ]},
      { key: "tasks", label: "Tasks / Work Queue", href: "/tasks", icon: "CheckSquare", moduleKey: "automation" },
    ],
  },
  {
    key: "processing",
    label: "Processing",
    labelTermKey: "processing",
    moduleKey: "manufacturing",
    tier: "primary",
    order: 0.5,
    items: [
      {
        key: "manufacturing-boms",
        label: "Bills of Material (BOM)",
        href: "/manufacturing/boms",
        icon: "List",
        moduleKey: "manufacturing",
        termKey: "bom",
        requiresFlags: ["bomMrpWorkOrders"],
        requiresPermissions: ["manufacturing.bom.read"],
      },
      {
        key: "manufacturing-routing",
        label: "Routing",
        href: "/manufacturing/routing",
        icon: "GitBranch",
        moduleKey: "manufacturing",
        requiresFlags: ["bomMrpWorkOrders"],
        requiresPermissions: ["manufacturing.production.read"],
      },
      {
        key: "manufacturing-work-orders",
        label: "Work Orders",
        href: "/manufacturing/work-orders",
        icon: "ClipboardList",
        moduleKey: "manufacturing",
        termKey: "workOrder",
        requiresFlags: ["workOrders"],
        requiresPermissions: ["manufacturing.workorders.read"],
      },
      {
        key: "manufacturing-mrp",
        label: "MRP",
        href: "/manufacturing/mrp",
        icon: "BarChart3",
        moduleKey: "manufacturing",
        requiresFlags: ["bomMrpWorkOrders"],
        requiresPermissions: ["manufacturing.production.read"],
      },
      {
        key: "manufacturing-subcontracting",
        label: "Subcontracting / Job Work",
        href: "/manufacturing/subcontracting",
        icon: "Factory",
        moduleKey: "manufacturing",
        requiresFlags: ["subcontracting"],
        requiresPermissions: ["manufacturing.production.read", "manufacturing.subcontracting.read"],
      },
      {
        key: "manufacturing-yield",
        label: "Yield / Mass balance",
        href: "/manufacturing/yield",
        icon: "Scale",
        moduleKey: "manufacturing",
        requiresFlags: ["massBalanceYield"],
        requiresPermissions: ["manufacturing.production.read", "manufacturing.subcontracting.read"],
      },
      {
        key: "manufacturing-byproducts",
        label: "Byproducts",
        href: "/manufacturing/byproducts",
        icon: "Package",
        moduleKey: "manufacturing",
        requiresFlags: ["reverseBom"],
        requiresPermissions: ["manufacturing.production.read"],
      },
    ],
  },
  {
    key: "masters",
    label: "Masters",
    moduleKey: "masters",
    tier: "secondary",
    order: 2,
    items: [
      { key: "masters-hub", label: "Masters", href: "/master", icon: "Database", moduleKey: "masters", requiresPermissions: ["inventory.read", "purchase.read", "sales.read"] },
      { key: "masters-products", label: "Products", href: "/master/products", icon: "Package", moduleKey: "masters", termKey: "product", requiresPermissions: ["inventory.read", "purchase.read", "sales.read"] },
      {
        key: "masters-categories",
        label: "Categories",
        href: "/master/categories",
        icon: "Tags",
        moduleKey: "masters",
        requiresPermissions: ["inventory.read", "purchase.read", "sales.read"],
      },
      {
        key: "masters-departments",
        label: "Departments",
        href: "/master/departments",
        icon: "Layers",
        moduleKey: "masters",
        requiresTemplates: ["fmcg-manufacturer", "fmcg-distributor", "retail-multi-store"],
        requiresPermissions: ["inventory.read", "purchase.read", "sales.read"],
      },
      { key: "masters-parties", label: "Parties", href: "/master/parties", icon: "Users", moduleKey: "masters", requiresPermissions: ["sales.read", "purchase.read", "finance.ar.read", "finance.ap.read"] },
      { key: "masters-warehouses", label: "Warehouses", href: "/master/warehouses", icon: "MapPin", moduleKey: "masters", termKey: "warehouse", requiresPermissions: ["inventory.read"] },
    ],
  },
  {
    key: "inventory",
    label: "Inventory",
    moduleKey: "inventory",
    tier: "primary",
    order: 3,
    items: [
      { key: "inventory-products", label: "Products", href: "/inventory/products", icon: "Package", moduleKey: "inventory", termKey: "product", requiresPermissions: ["inventory.read"] },
      { key: "inventory-stock-levels", label: "Stock Levels", href: "/inventory/stock-levels", icon: "Warehouse", moduleKey: "inventory", requiresPermissions: ["inventory.read"] },
      { key: "inventory-movements", label: "Stock Movements", href: "/inventory/movements", icon: "ArrowLeftRight", moduleKey: "inventory", requiresPermissions: ["inventory.read"] },
      { key: "inventory-receipts", label: "Receipts (GRN)", href: "/inventory/receipts", icon: "PackageCheck", moduleKey: "inventory", requiresPermissions: ["inventory.read"] },
      { key: "inventory-receiving", label: "Receiving Queue", href: "/inventory/receiving", icon: "ClipboardCheck", moduleKey: "inventory", requiresFlags: ["procurementAuditCashWeight"], requiresPermissions: ["inventory.read"] },
      { key: "inventory-costing", label: "Costing", href: "/inventory/costing", icon: "Calculator", moduleKey: "inventory", requiresPermissions: ["inventory.read"] },
      { key: "inventory-stock-explorer", label: "Stock Explorer", href: "/inventory/stock-explorer", icon: "Search", moduleKey: "inventory", requiresPermissions: ["inventory.read"] },
      { key: "inventory-valuation", label: "Valuation", href: "/inventory/valuation", icon: "Scale", moduleKey: "inventory", requiresPermissions: ["inventory.read"] },
      { key: "inventory-transfers", label: "Transfers", href: "/warehouse/transfers", icon: "Truck", moduleKey: "inventory", requiresFlags: ["multiWarehouse"], requiresPermissions: ["inventory.write"] },
      { key: "inventory-stocktake", label: "Stocktake / Cycle Count", href: "/warehouse/cycle-counts", icon: "ClipboardCheck", moduleKey: "inventory", requiresPermissions: ["inventory.write"] },
      { key: "inventory-warehouses", label: "Warehouses & Locations", href: "/inventory/warehouses", icon: "MapPin", moduleKey: "inventory", termKey: "warehouse", requiresPermissions: ["inventory.read"] },
    ],
  },
  {
    key: "warehouse",
    label: "Warehouse",
    moduleKey: "inventory",
    tier: "secondary",
    order: 4,
    items: [
      { key: "warehouse-overview", label: "Warehouse Overview", href: "/warehouse/overview", icon: "LayoutDashboard", moduleKey: "inventory", requiresPermissions: ["inventory.read"] },
      { key: "warehouse-transfers", label: "Transfers", href: "/warehouse/transfers", icon: "Truck", moduleKey: "inventory", requiresPermissions: ["inventory.write"] },
      { key: "warehouse-pick-pack", label: "Pick & Pack", href: "/warehouse/pick-pack", icon: "PackageCheck", moduleKey: "inventory", requiresPermissions: ["inventory.write"] },
      { key: "warehouse-dispatch-returns", label: "Driver returns", href: "/warehouse/dispatch-returns", icon: "Undo2", moduleKey: "inventory", requiresPermissions: ["inventory.write"] },
      { key: "warehouse-putaway", label: "Putaway", href: "/warehouse/putaway", icon: "MapPin", moduleKey: "inventory", requiresPermissions: ["inventory.write"] },
      { key: "warehouse-bin-locations", label: "Bin locations", href: "/warehouse/bin-locations", icon: "LayoutGrid", moduleKey: "inventory", requiresPermissions: ["inventory.read"] },
      { key: "warehouse-cycle-counts", label: "Cycle counts", href: "/warehouse/cycle-counts", icon: "ClipboardCheck", moduleKey: "inventory", requiresPermissions: ["inventory.write"] },
    ],
  },
  {
    key: "logistics",
    label: "Logistics",
    /** Fleet / outbound trip costing uses distribution module + API routes; reuse module gate. */
    moduleKey: "distribution",
    tier: "primary",
    requiresOrgTypes: ["DISTRIBUTOR"],
    order: 7.5,
    items: [
      {
        key: "logistics-trips",
        label: "Trips / Fleet",
        href: "/distribution/trips",
        icon: "Ship",
        moduleKey: "distribution",
        requiresFlags: ["logisticsTrips"],
        requiresPermissions: ["distribution.trips.read"],
      },
      {
        key: "logistics-dispatch-alerts",
        label: "Dispatch alerts",
        href: "/operations/dispatch-alerts",
        icon: "AlertTriangle",
        moduleKey: "distribution",
        requiresFlags: ["commissionEngine"],
        requiresPermissions: ["sales.deliveries.read", "franchise.network.read"],
      },
      {
        key: "logistics-fleet",
        label: "Manage fleet",
        href: "/distribution/logistics/fleet",
        icon: "Truck",
        moduleKey: "distribution",
        requiresFlags: ["logisticsTrips"],
        requiresPermissions: ["distribution.trips.write"],
      },
      {
        key: "logistics-outbound-logistics-dn",
        label: "DN outbound freight",
        href: "/distribution/logistics/delivery-note",
        icon: "Calculator",
        moduleKey: "distribution",
        requiresFlags: ["logisticsTrips"],
        requiresPermissions: ["logistics.dashboard.read", "distribution.trips.read"],
      },
      {
        key: "logistics-fuel-events",
        label: "Fuel audit",
        href: "/distribution/logistics/fuel",
        icon: "Fuel",
        moduleKey: "distribution",
        requiresFlags: ["logisticsTrips"],
        requiresPermissions: ["logistics.dashboard.read", "distribution.trips.read"],
      },
      {
        key: "logistics-vehicle-period-close",
        label: "Vehicle period close",
        href: "/distribution/logistics/period-close",
        icon: "Lock",
        moduleKey: "distribution",
        requiresFlags: ["logisticsTrips"],
        requiresPermissions: ["logistics.period.close"],
      },
      {
        key: "logistics-transfer-planning",
        label: "Transfer planning",
        href: "/distribution/transfer-planning",
        icon: "Route",
        moduleKey: "distribution",
        requiresFlags: ["logisticsTrips"],
        requiresPermissions: ["distribution.routes.read"],
      },
    ],
  },
  {
    key: "sales",
    label: "Sales",
    moduleKey: "sales",
    tier: "primary",
    order: 5,
    items: [
      { key: "sales-overview", label: "Sales Overview", href: "/sales/overview", icon: "LayoutDashboard", moduleKey: "sales", requiresPermissions: ["sales.read"] },
      { key: "sales-quotes", label: "Quotes", href: "/sales/quotes", icon: "FileText", moduleKey: "sales", requiresPermissions: ["sales.orders.read"] },
      { key: "sales-orders", label: "Orders", href: "/sales/orders", icon: "ShoppingCart", moduleKey: "sales", termKey: "salesOrder", requiresPermissions: ["sales.orders.read"] },
      { key: "sales-deliveries", label: "Deliveries", href: "/sales/deliveries", icon: "Truck", moduleKey: "sales", requiresPermissions: ["sales.deliveries.read"] },
      { key: "sales-invoices", label: "Invoices", href: "/sales/invoices", icon: "Receipt", moduleKey: "sales", requiresPermissions: ["sales.invoices.read"] },
      { key: "sales-customers", label: "Customers", href: "/sales/customers", icon: "Users", moduleKey: "sales", termKey: "customer", requiresPermissions: ["sales.customers.read"] },
      { key: "sales-returns", label: "Returns / Notes", href: "/sales/returns", icon: "RotateCcw", moduleKey: "sales", requiresPermissions: ["sales.returns.read"] },
    ],
  },
  {
    key: "purchasing",
    label: "Purchasing / Procurement",
    moduleKey: "purchasing",
    tier: "primary",
    order: 6,
    items: [
      { key: "purchasing-requests", label: "Purchase Requests", href: "/purchasing/requests", icon: "ClipboardList", moduleKey: "purchasing", requiresPermissions: ["purchase.read", "purchasing.orders.read"] },
      { key: "purchasing-orders", label: "Purchase Orders", href: "/purchasing/orders", icon: "FileText", moduleKey: "purchasing", termKey: "purchaseOrder", requiresPermissions: ["purchase.read", "purchasing.orders.read"] },
      { key: "purchasing-guided-sourcing-flow", label: "Guided Sourcing Flow", href: "/purchasing/sourcing-flow", icon: "Workflow", moduleKey: "purchasing", requiresPermissions: ["purchase.read", "purchasing.orders.read"] },
      { key: "purchasing-coolcatch-batches", label: "CoolCatch Sourcing Batches", href: "/purchasing/coolcatch-sourcing-batches", icon: "Fish", moduleKey: "purchasing", requiresFlags: ["commissionEngine"], requiresPermissions: ["purchase.read"] },
      { key: "purchasing-coolcatch-sourcing", label: "CoolCatch New Batch", href: "/purchasing/coolcatch-sourcing", icon: "PlusCircle", moduleKey: "purchasing", requiresFlags: ["commissionEngine"], requiresPermissions: ["purchase.write"] },
      { key: "purchasing-grn", label: "Goods Receipt (GRN)", href: "/inventory/receipts", icon: "PackageCheck", moduleKey: "purchasing", termKey: "goodsReceipt", requiresPermissions: ["purchasing.grn.read"] },
      { key: "purchasing-suppliers", label: "Suppliers", href: "/ap/suppliers", icon: "Building2", moduleKey: "purchasing", termKey: "supplier", requiresPermissions: ["purchasing.suppliers.read"] },
      { key: "purchasing-supplier-invoices", label: "Supplier Invoices (AP)", href: "/ap/bills", icon: "FileText", moduleKey: "purchasing", requiresPermissions: ["purchasing.bills.read"] },
      { key: "purchasing-returns", label: "Purchase Returns / Debit Notes", href: "/purchasing/purchase-returns", icon: "RotateCcw", moduleKey: "purchasing", requiresPermissions: ["purchasing.returns.read"] },
      { key: "purchasing-cash-weight-audit", label: "Cash-to-Weight Audit", href: "/purchasing/cash-weight-audit", icon: "Scale", moduleKey: "purchasing", requiresFlags: ["procurementAuditCashWeight"], requiresPermissions: ["purchase.read", "purchasing.orders.read"] },
    ],
  },
  {
    key: "distribution",
    label: "Distribution",
    moduleKey: "distribution",
    tier: "secondary",
    requiresOrgTypes: ["DISTRIBUTOR"],
    order: 8,
    items: [
      { key: "distribution-routes", label: "Routes", href: "/distribution/routes", icon: "MapPin", moduleKey: "distribution", termKey: "route", requiresPermissions: ["distribution.routes.read"] },
      { key: "distribution-deliveries", label: "Deliveries", href: "/distribution/deliveries", icon: "Truck", moduleKey: "distribution", termKey: "delivery", requiresFlags: ["deliveries"], requiresPermissions: ["distribution.deliveries.read"] },
      { key: "distribution-collections", label: "Collections", href: "/distribution/collections", icon: "Wallet", moduleKey: "distribution", termKey: "collection", requiresFlags: ["collections"], requiresPermissions: ["distribution.collections.read"] },
    ],
  },
  {
    key: "franchise",
    label: "Franchise",
    moduleKey: "franchise",
    tier: "secondary",
    order: 8.5,
    items: [
      {
        key: "franchise-network",
        label: "Franchise network",
        icon: "Network",
        moduleKey: "franchise",
        requiresFlags: ["franchiseNetworkMonitoring"],
        children: [
          {
            key: "franchise-network-outlets",
            label: "Outlets",
            href: "/franchise/network/outlets",
            icon: "Users",
            moduleKey: "franchise",
            requiresPermissions: ["franchise.network.read"],
          },
          {
            key: "franchise-network-overview",
            label: "Overview",
            href: "/franchise/network/overview",
            icon: "LayoutDashboard",
            moduleKey: "franchise",
            requiresFlags: ["commissionEngine"],
            requiresPermissions: ["inventory.read"],
          },
        ],
      },
      { key: "franchise-outlet-workspace", label: "Outlet Workspace", href: "/franchise/outlet", icon: "Store", moduleKey: "franchise", requiresFlags: ["franchiseLightErp"], requiresPermissions: ["sales.read"], requiresOrgRole: "FRANCHISEE" },
      { key: "franchise-commission", label: "Commission & Rebates", href: "/franchise/commission", icon: "Percent", moduleKey: "franchise", termKey: "commission", requiresFlags: ["commissionEngine", "franchiseSettlement"], requiresPermissions: ["franchise.commission.read"] },
      { key: "franchise-royalties", label: "Royalty billing", href: "/franchise/royalties", icon: "Banknote", moduleKey: "franchise", requiresFlags: ["commissionEngine", "franchiseSettlement"], requiresPermissions: ["franchise.commission.read"] },
      { key: "franchise-vmi", label: "VMI & Replenishment", href: "/franchise/vmi", icon: "PackagePlus", moduleKey: "franchise", requiresFlags: ["vmiReplenishment", "franchiseNetworkMonitoring"], requiresPermissions: ["inventory.read"] },
      { key: "franchise-comparison", label: "Performance Hub", href: "/franchise/comparison", icon: "BarChart3", moduleKey: "franchise", requiresFlags: ["franchiseNetworkAnalytics"], requiresPermissions: ["franchise.analytics.read"] },
      { key: "franchise-network-customers", label: "Network Customers", href: "/franchise/customers", icon: "Users2", moduleKey: "franchise", requiresFlags: ["franchiseNetworkMonitoring"], requiresPermissions: ["sales.customers.read"], requiresOrgRole: "FRANCHISOR" },
      { key: "franchise-chase-list", label: "Chase lists (BD leads)", href: "/franchise/chase-list", icon: "Users", moduleKey: "franchise", requiresFlags: ["franchiseNetworkMonitoring"], requiresPermissions: ["crm.deals.read", "franchise.network.read"] },
    ],
  },
  {
    key: "retail",
    label: "Retail",
    moduleKey: "retail",
    tier: "secondary",
    requiresOrgTypes: ["RETAIL"],
    order: 9,
    items: [
      { key: "retail-replenishment", label: "Replenishment", href: "/retail/replenishment", icon: "PackagePlus", moduleKey: "retail", termKey: "replenishment", requiresFlags: ["replenishment"], requiresPermissions: ["retail.replenishment.read"] },
      { key: "retail-promotions", label: "Promotions", href: "/retail/promotions", icon: "Tag", moduleKey: "retail", termKey: "promotion", requiresFlags: ["promotions"], requiresPermissions: ["retail.promotions.read"] },
      { key: "retail-store-performance", label: "Store Performance", href: "/retail/store-performance", icon: "BarChart3", moduleKey: "retail", termKey: "store", requiresFlags: ["storePerformance"], requiresPermissions: ["retail.performance.read"] },
    ],
  },
  {
    key: "assets",
    label: "Fixed Assets",
    moduleKey: "finance",
    tier: "secondary",
    order: 11,
    items: [
      { key: "assets-overview", label: "Assets Overview", href: "/assets/overview", icon: "LayoutDashboard", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "assets-register", label: "Asset register", href: "/assets/register", icon: "BookOpen", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "assets-depreciation", label: "Depreciation", href: "/assets/depreciation", icon: "TrendingDown", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "assets-disposals", label: "Disposals", href: "/assets/disposals", icon: "Trash2", moduleKey: "finance", requiresPermissions: ["finance.read"] },
    ],
  },
  {
    key: "projects",
    label: "Projects",
    moduleKey: "projects",
    tier: "secondary",
    order: 12,
    items: [
      { key: "projects-overview", label: "Projects Overview", href: "/projects/overview", icon: "LayoutDashboard", moduleKey: "projects", requiresPermissions: ["projects.read"] },
      { key: "projects-list", label: "Projects", href: "/projects/list", icon: "FolderKanban", moduleKey: "projects", requiresPermissions: ["projects.read"] },
      { key: "timesheets", label: "Timesheets", href: "/timesheets", icon: "Clock", moduleKey: "projects", requiresPermissions: ["projects.read"] },
    ],
  },
  {
    key: "intercompany",
    label: "Intercompany",
    moduleKey: "finance",
    tier: "secondary",
    order: 14,
    items: [
      { key: "intercompany-overview", label: "Intercompany Overview", href: "/intercompany/overview", icon: "LayoutDashboard", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "intercompany-transactions", label: "IC Transactions", href: "/intercompany/transactions", icon: "ArrowLeftRight", moduleKey: "finance", requiresPermissions: ["finance.read"] },
    ],
  },
  {
    key: "finance",
    label: "Finance & Accounting",
    moduleKey: "finance",
    tier: "primary",
    order: 15,
    items: [
      { key: "finance-dashboard", label: "Finance Dashboard", href: "/finance", icon: "TrendingUp", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "finance-gl", label: "General Ledger", href: "/finance/gl", icon: "BookOpen", moduleKey: "finance", requiresPermissions: ["finance.gl.read"] },
      { key: "finance-chart-of-accounts", label: "Chart of Accounts", href: "/finance/chart-of-accounts", icon: "ListTree", moduleKey: "finance", requiresPermissions: ["finance.accounts.read"] },
      { key: "finance-journals", label: "Journal Entries", href: "/finance/journals", icon: "FileEdit", moduleKey: "finance", requiresPermissions: ["finance.journals.read"] },
      { key: "finance-ar", label: "Accounts Receivable (AR)", href: "/finance/ar", icon: "ArrowDownCircle", moduleKey: "finance", requiresPermissions: ["finance.ar.read"] },
      { key: "ar-customers", label: "Customer credit", href: "/ar/customers", icon: "CreditCard", moduleKey: "finance", requiresPermissions: ["finance.ar.read"] },
      { key: "ar-payments", label: "AR Payments", href: "/ar/payments", icon: "CreditCard", moduleKey: "finance", requiresPermissions: ["finance.ar.read"] },
      { key: "finance-ap", label: "Accounts Payable (AP)", href: "/finance/ap", icon: "ArrowUpCircle", moduleKey: "finance", requiresPermissions: ["finance.ap.read"] },
      { key: "ap-suppliers", label: "AP Suppliers", href: "/ap/suppliers", icon: "Building2", moduleKey: "finance", requiresPermissions: ["finance.ap.read"] },
      { key: "ap-bills", label: "AP Bills", href: "/ap/bills", icon: "Receipt", moduleKey: "finance", requiresPermissions: ["finance.ap.read"] },
      { key: "ap-payments", label: "AP Payments", href: "/ap/payments", icon: "CreditCard", moduleKey: "finance", requiresPermissions: ["finance.ap.read"] },
      { key: "ap-three-way-match", label: "3-way match", href: "/ap/three-way-match", icon: "GitCompare", moduleKey: "finance", requiresPermissions: ["finance.ap.read"] },
      { key: "finance-payments", label: "Payments & Receipts", href: "/finance/payments", icon: "CreditCard", moduleKey: "finance", requiresPermissions: ["finance.payments.read"] },
      { key: "finance-tax", label: "Tax / VAT", href: "/finance/tax", icon: "Receipt", moduleKey: "finance", requiresPermissions: ["finance.tax.read"] },
      { key: "finance-procurement-review", label: "Procurement Review", href: "/finance/procurement-review", icon: "ClipboardList", moduleKey: "finance", requiresFlags: ["procurementAuditCashWeight"], requiresPermissions: ["finance.read"] },
      { key: "finance-bank-recon", label: "Bank Reconciliation", href: "/finance/bank-recon", icon: "Wallet", moduleKey: "finance", requiresPermissions: ["finance.bank.read"] },
      { key: "finance-mpesa-recon", label: "M-Pesa Till Reconciliation", href: "/finance/mpesa-recon", icon: "Smartphone", moduleKey: "finance", requiresFlags: ["procurementAuditCashWeight"], requiresPermissions: ["finance.read"] },
      { key: "finance-coolcatch-bs", label: "CoolCatch BS Inventory", href: "/finance/coolcatch-bs-inventory", icon: "Layers", moduleKey: "finance", requiresFlags: ["commissionEngine"], requiresPermissions: ["finance.read", "inventory.read"] },
      { key: "finance-coolcatch-month-end", label: "CoolCatch Month-End", href: "/finance/coolcatch-month-end", icon: "CalendarCheck", moduleKey: "finance", requiresFlags: ["commissionEngine"], requiresPermissions: ["finance.write"] },
      { key: "finance-coolcatch-etims", label: "CoolCatch eTIMS", href: "/finance/coolcatch-etims", icon: "Receipt", moduleKey: "finance", requiresFlags: ["commissionEngine"], requiresPermissions: ["sales.write"] },
      { key: "finance-commission-topup", label: "Commission / Top-up", href: "/finance/commission-topup", icon: "Percent", moduleKey: "finance", requiresFlags: ["commissionEngine"], requiresPermissions: ["finance.read"] },
      { key: "finance-journal-events", label: "Journal Events", href: "/finance/journal-events", icon: "BookOpen", moduleKey: "finance", requiresFlags: ["commissionEngine"], requiresPermissions: ["finance.journals.read"] },
      { key: "finance-statements", label: "Financial Statements", href: "/finance/statements", icon: "BarChart3", moduleKey: "finance", requiresPermissions: ["finance.statements.read"], children: [
        { key: "finance-statements-pnl", label: "P&L", href: "/finance/statements/pnl", icon: "TrendingUp", moduleKey: "finance", requiresPermissions: ["finance.statements.read"] },
        { key: "finance-statements-balance-sheet", label: "Balance Sheet", href: "/finance/statements/balance-sheet", icon: "Scale", moduleKey: "finance", requiresPermissions: ["finance.statements.read"] },
        { key: "finance-statements-cash-flow", label: "Cash Flow", href: "/finance/statements/cash-flow", icon: "ArrowLeftRight", moduleKey: "finance", requiresPermissions: ["finance.statements.read"] },
      ]},
      { key: "finance-trial-balance", label: "Trial Balance", href: "/finance/trial-balance", icon: "Scale", moduleKey: "finance", requiresPermissions: ["finance.gl.read"] },
      { key: "finance-period-close", label: "Period Close", href: "/finance/period-close", icon: "Lock", moduleKey: "finance", requiresPermissions: ["finance.close.write"] },
      { key: "finance-budgets", label: "Budgets", href: "/finance/budgets", icon: "PiggyBank", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "finance-ledger", label: "Ledger", href: "/finance/ledger", icon: "BookOpen", moduleKey: "finance", requiresPermissions: ["finance.gl.read"] },
      { key: "finance-audit", label: "Audit Log", href: "/finance/audit", icon: "FileSearch", moduleKey: "finance", requiresPermissions: ["finance.audit.read"] },
      {
        key: "payroll",
        label: "Payroll",
        icon: "Wallet",
        moduleKey: "finance",
        requiresPermissions: ["finance.read"],
        children: [
          { key: "payroll-overview", label: "Payroll Overview", href: "/payroll/overview", icon: "LayoutDashboard", moduleKey: "finance", requiresPermissions: ["finance.read"] },
          { key: "payroll-employees", label: "Employees", href: "/payroll/employees", icon: "Users", moduleKey: "finance", requiresPermissions: ["finance.read"] },
          { key: "payroll-leave", label: "Leave", href: "/payroll/leave", icon: "Palmtree", moduleKey: "finance", requiresPermissions: ["finance.read"] },
          { key: "payroll-payruns", label: "Pay runs", href: "/payroll/pay-runs", icon: "CreditCard", moduleKey: "finance", requiresPermissions: ["finance.read"] },
          { key: "payroll-payslips", label: "Payslips", href: "/payroll/payslips", icon: "FileText", moduleKey: "finance", requiresPermissions: ["finance.read"] },
          { key: "payroll-p9", label: "P9 Forms", href: "/payroll/p9", icon: "ClipboardList", moduleKey: "finance", requiresPermissions: ["finance.read"] },
          { key: "payroll-statutories", label: "Statutories", href: "/payroll/statutories", icon: "ShieldCheck", moduleKey: "finance", requiresPermissions: ["finance.read"] },
        ],
      },
    ],
  },
  {
    key: "pricing",
    label: "Pricing",
    moduleKey: "pricing",
    tier: "primary",
    order: 6.3,
    items: [
      {
        key: "pricing-workspace",
        label: "Pricing workspace",
        icon: "LayoutDashboard",
        moduleKey: "pricing",
        requiresPermissions: ["sales.write", "admin.settings"],
        children: [
          {
            key: "pricing-workspace-overview",
            label: "Overview",
            href: "/pricing/workspace/overview",
            icon: "LayoutDashboard",
            moduleKey: "pricing",
            requiresPermissions: ["sales.write", "admin.settings"],
          },
          {
            key: "pricing-workspace-lists",
            label: "Price lists",
            href: "/pricing/workspace/lists",
            icon: "List",
            moduleKey: "pricing",
            requiresPermissions: ["sales.write", "admin.settings"],
          },
          {
            key: "pricing-workspace-packs",
            label: "Packs",
            href: "/pricing/workspace/packs",
            icon: "Package",
            moduleKey: "pricing",
            requiresPermissions: ["sales.write", "admin.settings"],
            /** FMCG piece×pack pricing — manufacturer sell packs. */
            requiresTemplates: ["fmcg-manufacturer", "fmcg-distributor", "retail-multi-store"],
          },
          {
            key: "pricing-workspace-tax-tags",
            label: "Tax tags",
            href: "/pricing/workspace/tax-tags",
            icon: "Receipt",
            moduleKey: "pricing",
            requiresPermissions: ["sales.write", "admin.settings"],
            /** FMCG VAT configurations (exclusive / inclusive) for invoicing. */
            requiresTemplates: ["fmcg-manufacturer", "fmcg-distributor", "retail-multi-store"],
          },
          {
            key: "pricing-workspace-zones",
            label: "Franchise zones",
            href: "/pricing/workspace/zones",
            icon: "MapPin",
            moduleKey: "pricing",
            requiresPermissions: ["sales.write", "admin.settings"],
            /** CoolCatch / seafood franchise pricing — hidden for FMCG. */
            requiresTemplates: ["seafood-distributor", "cool-catch", "coolcatch"],
          },
          {
            key: "pricing-workspace-approvals",
            label: "Approvals",
            href: "/pricing/workspace/approvals",
            icon: "ClipboardCheck",
            moduleKey: "pricing",
            requiresPermissions: ["sales.write", "admin.settings"],
            /** CoolCatch daily price review — seafood only. */
            requiresTemplates: ["seafood-distributor", "cool-catch", "coolcatch"],
          },
        ],
      },
      { key: "pricing-rules", label: "Pricing rules", href: "/pricing/rules", icon: "Workflow", moduleKey: "pricing", requiresPermissions: ["sales.write", "admin.settings"] },
    ],
  },
  {
    key: "docs",
    label: "Document Center",
    moduleKey: "docs",
    tier: "primary",
    order: 6.4,
    items: [
      { key: "docs-hub", label: "Documents", href: "/docs", icon: "FileText", moduleKey: "docs", requiresPermissions: ["sales.read", "purchase.read", "finance.read"] },
      { key: "docs-so", label: "Sales Orders", href: "/docs/sales-order", icon: "ShoppingCart", moduleKey: "docs", termKey: "salesOrder", requiresPermissions: ["sales.orders.read", "sales.read"] },
      { key: "docs-po", label: "Purchase Orders", href: "/docs/purchase-order", icon: "FileText", moduleKey: "docs", termKey: "purchaseOrder", requiresPermissions: ["purchasing.orders.read", "purchase.read"] },
      { key: "docs-grn", label: "Goods Receipt", href: "/docs/grn", icon: "PackageCheck", moduleKey: "docs", termKey: "goodsReceipt", requiresPermissions: ["purchasing.grn.read", "purchase.read"] },
      { key: "docs-invoice", label: "Invoices", href: "/docs/invoice", icon: "Receipt", moduleKey: "docs", termKey: "invoice", requiresPermissions: ["sales.invoices.read", "finance.read"] },
      { key: "docs-credit-note", label: "Sales Credit Notes", href: "/docs/credit-note", icon: "RotateCcw", moduleKey: "docs", requiresPermissions: ["sales.returns.read"] },
      { key: "docs-debit-note", label: "Sales Debit Notes", href: "/docs/debit-note", icon: "BadgePlus", moduleKey: "docs", requiresPermissions: ["sales.returns.read"] },
      { key: "docs-purchase-credit-note", label: "Purchase Credit Notes", href: "/docs/purchase-credit-note", icon: "RotateCcw", moduleKey: "docs", requiresPermissions: ["purchasing.bills.read"] },
      { key: "docs-purchase-debit-note", label: "Purchase Debit Notes", href: "/docs/purchase-debit-note", icon: "BadgePlus", moduleKey: "docs", requiresPermissions: ["purchasing.returns.read"] },
      { key: "docs-journal", label: "Journal Entries", href: "/docs/journal", icon: "FileEdit", moduleKey: "docs", termKey: "journalEntry", requiresPermissions: ["finance.journals.read", "finance.read"] },
    ],
  },
  {
    key: "treasury",
    label: "Treasury",
    moduleKey: "finance",
    tier: "secondary",
    order: 10,
    items: [
      { key: "treasury-overview", label: "Treasury Overview", href: "/treasury/overview", icon: "LayoutDashboard", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "treasury-payment-runs", label: "Payment runs", href: "/treasury/payment-runs", icon: "CreditCard", moduleKey: "finance", requiresPermissions: ["finance.ap.read"] },
      { key: "treasury-collections", label: "Collections", href: "/treasury/collections", icon: "Receipt", moduleKey: "finance", requiresPermissions: ["finance.ar.read"] },
      { key: "ar-aging", label: "AR Aging Report", href: "/ar/aging", icon: "BarChart2", moduleKey: "finance", requiresPermissions: ["finance.ar.read"] },
      { key: "treasury-bank-accounts", label: "Bank accounts", href: "/treasury/bank-accounts", icon: "Landmark", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "treasury-cashflow", label: "Cashflow", href: "/treasury/cashflow", icon: "TrendingUp", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "finance-bank-recon", label: "Bank Reconciliation", href: "/finance/bank-recon", icon: "Wallet", moduleKey: "finance", requiresPermissions: ["finance.bank.read"] },
    ],
  },
  {
    key: "crm",
    label: "CRM",
    moduleKey: "crm",
    tier: "secondary",
    order: 16,
    items: [
      { key: "crm-accounts", label: "Accounts / Parties", href: "/crm/accounts", icon: "Building2", moduleKey: "crm", requiresPermissions: ["crm.accounts.read"] },
      { key: "crm-activities", label: "Activities / Notes", href: "/crm/activities", icon: "StickyNote", moduleKey: "crm", requiresPermissions: ["crm.activities.read"] },
      { key: "crm-deals", label: "Deals / Opportunities", href: "/crm/deals", icon: "TrendingUp", moduleKey: "crm", requiresPermissions: ["crm.deals.read"] },
      { key: "crm-tickets", label: "Support / Tickets", href: "/crm/tickets", icon: "Ticket", moduleKey: "crm", requiresPermissions: ["crm.tickets.read"] },
    ],
  },
  {
    key: "reports",
    label: "Reports",
    moduleKey: "reports",
    tier: "secondary",
    order: 17,
    items: [
      { key: "reports-library", label: "Report Library", href: "/reports", icon: "FileText", moduleKey: "reports", requiresPermissions: ["reports.read"] },
      { key: "reports-saved", label: "Saved Views", href: "/reports/saved", icon: "Bookmark", moduleKey: "reports", requiresPermissions: ["reports.read"] },
      { key: "reports-scheduled", label: "Scheduled Reports", href: "/reports/scheduled", icon: "Clock", moduleKey: "reports", requiresPermissions: ["reports.schedule.read"] },
      { key: "reports-exports", label: "Exports", href: "/reports/exports", icon: "Download", moduleKey: "reports", requiresPermissions: ["reports.export.read"] },
      { key: "reports-vat", label: "VAT Summary", href: "/reports/vat-summary", icon: "Receipt", moduleKey: "reports", requiresPermissions: ["reports.read"] },
      { key: "reports-wht", label: "WHT Summary", href: "/reports/wht-summary", icon: "Percent", moduleKey: "reports", requiresPermissions: ["reports.read"] },
    ],
  },
  {
    key: "analytics",
    label: "Analytics",
    moduleKey: "analytics",
    tier: "secondary",
    order: 18,
    items: [
      { key: "analytics-hub", label: "Analytics Studio", href: "/analytics", icon: "BarChart3", moduleKey: "analytics", requiresPermissions: ["reports.read", "admin.settings"] },
      { key: "analytics-explore", label: "Explore", href: "/analytics/explore", icon: "Compass", moduleKey: "analytics", requiresPermissions: ["reports.read", "admin.settings"] },
      { key: "analytics-insights", label: "Insights", href: "/analytics/insights", icon: "Lightbulb", moduleKey: "analytics", requiresPermissions: ["reports.read", "admin.settings"] },
      { key: "analytics-anomalies", label: "Anomalies", href: "/analytics/anomalies", icon: "AlertTriangle", moduleKey: "analytics", requiresPermissions: ["reports.read", "admin.settings"] },
      { key: "analytics-simulations", label: "Simulations", href: "/analytics/simulations", icon: "SlidersHorizontal", moduleKey: "analytics", requiresPermissions: ["reports.read", "admin.settings"] },
      { key: "analytics-products", label: "Products", href: "/analytics/products", icon: "Package", moduleKey: "analytics", requiresPermissions: ["reports.read", "admin.settings"] },
      { key: "analytics-pricing", label: "Pricing", href: "/analytics/pricing", icon: "TrendingUp", moduleKey: "analytics", requiresPermissions: ["reports.read", "admin.settings"] },
      { key: "analytics-inventory", label: "Inventory", href: "/analytics/inventory", icon: "Warehouse", moduleKey: "analytics", requiresPermissions: ["reports.read", "admin.settings"] },
      { key: "analytics-finance", label: "Finance", href: "/analytics/finance", icon: "Landmark", moduleKey: "analytics", requiresPermissions: ["reports.read", "finance.read"] },
      { key: "analytics-payroll", label: "Payroll", href: "/analytics/payroll", icon: "CreditCard", moduleKey: "analytics", requiresPermissions: ["reports.read", "admin.settings"] },
      { key: "analytics-settings", label: "Analytics settings", href: "/analytics/settings", icon: "Settings", moduleKey: "analytics", requiresPermissions: ["admin.settings"] },
    ],
  },
  {
    key: "automation",
    label: "Automation Center",
    moduleKey: "automation",
    tier: "secondary",
    order: 19,
    items: [
      { key: "automation-dashboard", label: "Automation Dashboard", href: "/automation", icon: "Zap", moduleKey: "automation", requiresPermissions: ["automation.read"] },
      { key: "automation-rules", label: "Rules Engine", href: "/automation/rules", icon: "Workflow", moduleKey: "automation", requiresPermissions: ["automation.rules.read"] },
      { key: "automation-alerts", label: "Alerts & Notifications", href: "/automation/alerts", icon: "Bell", moduleKey: "automation", requiresPermissions: ["automation.alerts.read"], badge: { type: "count", value: "3" } },
      { key: "automation-schedules", label: "Scheduled Jobs", href: "/automation/schedules", icon: "Calendar", moduleKey: "automation", requiresPermissions: ["automation.schedules.read"] },
      { key: "automation-workflows", label: "Approvals Workflows", href: "/automation/workflows", icon: "CheckCircle2", moduleKey: "automation", requiresPermissions: ["automation.workflows.read"] },
      { key: "automation-integrations", label: "Integrations", href: "/automation/integrations", icon: "Plug", moduleKey: "automation", requiresPermissions: ["automation.integrations.read"] },
      { key: "automation-ai-insights", label: "AI Insights", href: "/automation/ai-insights", icon: "Brain", moduleKey: "automation", requiresPermissions: ["automation.ai.read"], requiresFlags: ["copilot"], badge: { type: "text", value: "NEW" } },
      { key: "work-queue", label: "Work queue", href: "/work/queue", icon: "ListTodo", moduleKey: "automation", requiresPermissions: ["automation.read"] },
    ],
  },

];
