import type { NavSectionConfig } from "./types";

export const NAV_SECTIONS_CONFIG: NavSectionConfig[] = [
  {
    key: "core",
    label: "Core",
    moduleKey: "dashboard",
    order: 0,
    items: [
      { key: "dashboard", label: "Dashboard", href: "/dashboard", icon: "LayoutDashboard", moduleKey: "dashboard" },
      { key: "approvals", label: "Approvals", href: "/approvals", icon: "CheckCircle2", moduleKey: "automation", requiresFlags: ["approvals"], requiresPermissions: ["approvals.read"], children: [
        { key: "approvals-inbox", label: "Inbox", href: "/approvals/inbox", icon: "Inbox", moduleKey: "automation", requiresPermissions: ["approvals.read"] },
        { key: "approvals-requests", label: "My requests", href: "/approvals/requests", icon: "Send", moduleKey: "automation", requiresPermissions: ["approvals.read"] },
      ]},
      { key: "tasks", label: "Tasks / Work Queue", href: "/tasks", icon: "CheckSquare", moduleKey: "automation" },
    ],
  },
  {
    key: "docs",
    label: "Document Center",
    moduleKey: "docs",
    order: 1,
    items: [
      { key: "docs-hub", label: "Documents", href: "/docs", icon: "FileText", moduleKey: "docs" },
      { key: "docs-so", label: "Sales Orders", href: "/docs/sales-order", icon: "ShoppingCart", moduleKey: "docs", termKey: "salesOrder" },
      { key: "docs-po", label: "Purchase Orders", href: "/docs/purchase-order", icon: "FileText", moduleKey: "docs", termKey: "purchaseOrder" },
      { key: "docs-grn", label: "Goods Receipt", href: "/docs/grn", icon: "PackageCheck", moduleKey: "docs", termKey: "goodsReceipt" },
      { key: "docs-invoice", label: "Invoices", href: "/docs/invoice", icon: "Receipt", moduleKey: "docs", termKey: "invoice" },
      { key: "docs-journal", label: "Journal Entries", href: "/docs/journal", icon: "FileEdit", moduleKey: "docs", termKey: "journalEntry" },
    ],
  },
  {
    key: "masters",
    label: "Masters",
    moduleKey: "masters",
    order: 2,
    items: [
      { key: "masters-hub", label: "Masters", href: "/master", icon: "Database", moduleKey: "masters" },
      { key: "masters-products", label: "Products", href: "/master/products", icon: "Package", moduleKey: "masters", termKey: "product" },
      { key: "masters-parties", label: "Parties", href: "/master/parties", icon: "Users", moduleKey: "masters" },
      { key: "masters-warehouses", label: "Warehouses", href: "/master/warehouses", icon: "MapPin", moduleKey: "masters", termKey: "warehouse" },
    ],
  },
  {
    key: "inventory",
    label: "Inventory",
    moduleKey: "inventory",
    order: 3,
    items: [
      { key: "inventory-products", label: "Products", href: "/inventory/products", icon: "Package", moduleKey: "inventory", termKey: "product", requiresPermissions: ["inventory.read"] },
      { key: "inventory-stock-levels", label: "Stock Levels", href: "/inventory/stock-levels", icon: "Warehouse", moduleKey: "inventory", requiresPermissions: ["inventory.read"] },
      { key: "inventory-movements", label: "Stock Movements", href: "/inventory/movements", icon: "ArrowLeftRight", moduleKey: "inventory", requiresPermissions: ["inventory.read"] },
      { key: "inventory-receipts", label: "Receipts (GRN)", href: "/inventory/receipts", icon: "PackageCheck", moduleKey: "inventory", requiresPermissions: ["inventory.read"] },
      { key: "inventory-costing", label: "Costing", href: "/inventory/costing", icon: "Calculator", moduleKey: "inventory", requiresPermissions: ["inventory.read"] },
      { key: "inventory-transfers", label: "Transfers", href: "/warehouse/transfers", icon: "Truck", moduleKey: "inventory", requiresFlags: ["multiWarehouse"], requiresPermissions: ["inventory.write"] },
      { key: "inventory-stocktake", label: "Stocktake / Cycle Count", href: "/warehouse/cycle-counts", icon: "ClipboardCheck", moduleKey: "inventory", requiresPermissions: ["inventory.write"] },
      { key: "inventory-warehouses", label: "Warehouses & Locations", href: "/inventory/warehouses", icon: "MapPin", moduleKey: "inventory", termKey: "warehouse", requiresPermissions: ["inventory.read"] },
    ],
  },
  {
    key: "warehouse",
    label: "Warehouse",
    moduleKey: "inventory",
    order: 4,
    items: [
      { key: "warehouse-overview", label: "Warehouse Overview", href: "/warehouse/overview", icon: "LayoutDashboard", moduleKey: "inventory", requiresPermissions: ["inventory.read"] },
      { key: "warehouse-transfers", label: "Transfers", href: "/warehouse/transfers", icon: "Truck", moduleKey: "inventory", requiresPermissions: ["inventory.write"] },
      { key: "warehouse-pick-pack", label: "Pick & Pack", href: "/warehouse/pick-pack", icon: "PackageCheck", moduleKey: "inventory", requiresPermissions: ["inventory.write"] },
      { key: "warehouse-putaway", label: "Putaway", href: "/warehouse/putaway", icon: "MapPin", moduleKey: "inventory", requiresPermissions: ["inventory.write"] },
      { key: "warehouse-bin-locations", label: "Bin locations", href: "/warehouse/bin-locations", icon: "LayoutGrid", moduleKey: "inventory", requiresPermissions: ["inventory.read"] },
      { key: "warehouse-cycle-counts", label: "Cycle counts", href: "/warehouse/cycle-counts", icon: "ClipboardCheck", moduleKey: "inventory", requiresPermissions: ["inventory.write"] },
    ],
  },
  {
    key: "sales",
    label: "Sales",
    moduleKey: "sales",
    order: 5,
    items: [
      { key: "sales-overview", label: "Sales Overview", href: "/sales/overview", icon: "LayoutDashboard", moduleKey: "sales", requiresPermissions: ["sales.read"] },
      { key: "sales-quotes", label: "Quotes", href: "/sales/quotes", icon: "FileText", moduleKey: "sales", requiresPermissions: ["sales.orders.read"] },
      { key: "sales-orders", label: "Orders", href: "/sales/orders", icon: "ShoppingCart", moduleKey: "sales", termKey: "salesOrder", requiresPermissions: ["sales.orders.read"] },
      { key: "sales-deliveries", label: "Deliveries", href: "/sales/deliveries", icon: "Truck", moduleKey: "sales", requiresPermissions: ["sales.deliveries.read"] },
      { key: "sales-invoices", label: "Invoices", href: "/sales/invoices", icon: "Receipt", moduleKey: "sales", requiresPermissions: ["sales.invoices.read"] },
      { key: "sales-customers", label: "Customers", href: "/sales/customers", icon: "Users", moduleKey: "sales", termKey: "customer", requiresPermissions: ["sales.customers.read"] },
      { key: "sales-returns", label: "Returns / Credit Notes", href: "/sales/returns", icon: "RotateCcw", moduleKey: "sales", requiresPermissions: ["sales.returns.read"] },
    ],
  },
  {
    key: "purchasing",
    label: "Purchasing / Procurement",
    moduleKey: "purchasing",
    order: 6,
    items: [
      { key: "purchasing-requests", label: "Purchase Requests", href: "/purchasing/requests", icon: "ClipboardList", moduleKey: "purchasing", requiresPermissions: ["purchasing.orders.read"] },
      { key: "purchasing-orders", label: "Purchase Orders", href: "/purchasing/orders", icon: "FileText", moduleKey: "purchasing", termKey: "purchaseOrder", requiresPermissions: ["purchasing.orders.read"] },
      { key: "purchasing-grn", label: "Goods Receipt (GRN)", href: "/inventory/receipts", icon: "PackageCheck", moduleKey: "purchasing", termKey: "goodsReceipt", requiresPermissions: ["purchasing.grn.read"] },
      { key: "purchasing-suppliers", label: "Suppliers", href: "/ap/suppliers", icon: "Building2", moduleKey: "purchasing", termKey: "supplier", requiresPermissions: ["purchasing.suppliers.read"] },
      { key: "purchasing-supplier-invoices", label: "Supplier Invoices (AP)", href: "/ap/bills", icon: "FileText", moduleKey: "purchasing", requiresPermissions: ["purchasing.bills.read"] },
      { key: "purchasing-returns", label: "Purchase Returns", href: "/purchasing/purchase-returns", icon: "RotateCcw", moduleKey: "purchasing", requiresPermissions: ["purchasing.returns.read"] },
    ],
  },
  {
    key: "pricing",
    label: "Pricing",
    moduleKey: "pricing",
    order: 6.5,
    items: [
      { key: "pricing-overview", label: "Pricing Overview", href: "/pricing/overview", icon: "LayoutDashboard", moduleKey: "pricing" },
      { key: "pricing-price-lists", label: "Price Lists", href: "/pricing/price-lists", icon: "List", moduleKey: "pricing" },
      { key: "pricing-rules", label: "Pricing Rules", href: "/pricing/rules", icon: "Workflow", moduleKey: "pricing" },
    ],
  },
  {
    key: "manufacturing",
    label: "Manufacturing",
    moduleKey: "manufacturing",
    requiresOrgTypes: ["MANUFACTURER"],
    order: 7,
    items: [
      { key: "manufacturing-boms", label: "Bills of Material (BOM)", href: "/manufacturing/boms", icon: "List", moduleKey: "manufacturing", termKey: "bom", requiresFlags: ["bomMrpWorkOrders"], requiresPermissions: ["manufacturing.bom.read"] },
      { key: "manufacturing-routing", label: "Routing", href: "/manufacturing/routing", icon: "GitBranch", moduleKey: "manufacturing", requiresFlags: ["bomMrpWorkOrders"], requiresPermissions: ["manufacturing.production.read"] },
      { key: "manufacturing-work-orders", label: "Work Orders", href: "/manufacturing/work-orders", icon: "ClipboardList", moduleKey: "manufacturing", termKey: "workOrder", requiresFlags: ["workOrders"], requiresPermissions: ["manufacturing.workorders.read"] },
      { key: "manufacturing-mrp", label: "MRP", href: "/manufacturing/mrp", icon: "BarChart3", moduleKey: "manufacturing", requiresFlags: ["bomMrpWorkOrders"], requiresPermissions: ["manufacturing.production.read"] },
    ],
  },
  {
    key: "distribution",
    label: "Distribution",
    moduleKey: "distribution",
    requiresOrgTypes: ["DISTRIBUTOR"],
    order: 8,
    items: [
      { key: "distribution-routes", label: "Routes", href: "/distribution/routes", icon: "MapPin", moduleKey: "distribution", termKey: "route", requiresPermissions: ["distribution.routes.read"] },
      { key: "distribution-deliveries", label: "Deliveries", href: "/distribution/deliveries", icon: "Truck", moduleKey: "distribution", termKey: "delivery", requiresFlags: ["deliveries"], requiresPermissions: ["distribution.deliveries.read"] },
      { key: "distribution-collections", label: "Collections", href: "/distribution/collections", icon: "Wallet", moduleKey: "distribution", termKey: "collection", requiresFlags: ["collections"], requiresPermissions: ["distribution.collections.read"] },
    ],
  },
  {
    key: "retail",
    label: "Retail",
    moduleKey: "retail",
    requiresOrgTypes: ["RETAIL"],
    order: 9,
    items: [
      { key: "retail-replenishment", label: "Replenishment", href: "/retail/replenishment", icon: "PackagePlus", moduleKey: "retail", termKey: "replenishment", requiresFlags: ["replenishment"], requiresPermissions: ["retail.replenishment.read"] },
      { key: "retail-promotions", label: "Promotions", href: "/retail/promotions", icon: "Tag", moduleKey: "retail", termKey: "promotion", requiresFlags: ["promotions"], requiresPermissions: ["retail.promotions.read"] },
      { key: "retail-store-performance", label: "Store Performance", href: "/retail/store-performance", icon: "BarChart3", moduleKey: "retail", termKey: "store", requiresFlags: ["storePerformance"], requiresPermissions: ["retail.performance.read"] },
    ],
  },
  {
    key: "treasury",
    label: "Treasury",
    moduleKey: "finance",
    order: 10,
    items: [
      { key: "treasury-overview", label: "Treasury Overview", href: "/treasury/overview", icon: "LayoutDashboard", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "treasury-payment-runs", label: "Payment runs", href: "/treasury/payment-runs", icon: "CreditCard", moduleKey: "finance", requiresPermissions: ["finance.ap.read"] },
      { key: "treasury-collections", label: "Collections", href: "/treasury/collections", icon: "Receipt", moduleKey: "finance", requiresPermissions: ["finance.ar.read"] },
      { key: "treasury-bank-accounts", label: "Bank accounts", href: "/treasury/bank-accounts", icon: "Landmark", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "treasury-cashflow", label: "Cashflow", href: "/treasury/cashflow", icon: "TrendingUp", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "finance-bank-recon", label: "Bank Reconciliation", href: "/finance/bank-recon", icon: "Wallet", moduleKey: "finance", requiresPermissions: ["finance.bank.read"] },
    ],
  },
  {
    key: "assets",
    label: "Fixed Assets",
    moduleKey: "finance",
    order: 11,
    items: [
      { key: "assets-overview", label: "Assets Overview", href: "/assets/overview", icon: "LayoutDashboard", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "assets-register", label: "Asset register", href: "/assets/register", icon: "BookOpen", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "assets-depreciation", label: "Depreciation", href: "/assets/depreciation", icon: "TrendingDown", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "assets-disposals", label: "Disposals", href: "/assets/disposals", icon: "Trash2", moduleKey: "finance", requiresPermissions: ["finance.read"] },
    ],
  },
  {
    key: "projects",
    label: "Projects",
    moduleKey: "projects",
    order: 12,
    items: [
      { key: "projects-overview", label: "Projects Overview", href: "/projects/overview", icon: "LayoutDashboard", moduleKey: "projects", requiresPermissions: ["projects.read"] },
      { key: "projects-list", label: "Projects", href: "/projects/list", icon: "FolderKanban", moduleKey: "projects", requiresPermissions: ["projects.read"] },
      { key: "timesheets", label: "Timesheets", href: "/timesheets", icon: "Clock", moduleKey: "projects", requiresPermissions: ["projects.read"] },
    ],
  },
  {
    key: "payroll",
    label: "Payroll",
    moduleKey: "finance",
    order: 13,
    items: [
      { key: "payroll-overview", label: "Payroll Overview", href: "/payroll/overview", icon: "LayoutDashboard", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "payroll-employees", label: "Employees", href: "/payroll/employees", icon: "Users", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "payroll-payruns", label: "Pay runs", href: "/payroll/pay-runs", icon: "CreditCard", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "payroll-payslips", label: "Payslips", href: "/payroll/payslips", icon: "FileText", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "payroll-statutories", label: "Statutories", href: "/payroll/statutories", icon: "ShieldCheck", moduleKey: "finance", requiresPermissions: ["finance.read"] },
    ],
  },
  {
    key: "intercompany",
    label: "Intercompany",
    moduleKey: "finance",
    order: 14,
    items: [
      { key: "intercompany-overview", label: "Intercompany Overview", href: "/intercompany/overview", icon: "LayoutDashboard", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "intercompany-transactions", label: "IC Transactions", href: "/intercompany/transactions", icon: "ArrowLeftRight", moduleKey: "finance", requiresPermissions: ["finance.read"] },
    ],
  },
  {
    key: "finance",
    label: "Finance & Accounting",
    moduleKey: "finance",
    order: 15,
    items: [
      { key: "finance-dashboard", label: "Finance Dashboard", href: "/finance", icon: "TrendingUp", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "finance-gl", label: "General Ledger", href: "/finance/gl", icon: "BookOpen", moduleKey: "finance", requiresPermissions: ["finance.gl.read"] },
      { key: "finance-chart-of-accounts", label: "Chart of Accounts", href: "/finance/chart-of-accounts", icon: "ListTree", moduleKey: "finance", requiresPermissions: ["finance.accounts.read"] },
      { key: "finance-journals", label: "Journal Entries", href: "/finance/journals", icon: "FileEdit", moduleKey: "finance", requiresPermissions: ["finance.journals.read"] },
      { key: "finance-ar", label: "Accounts Receivable (AR)", href: "/finance/ar", icon: "ArrowDownCircle", moduleKey: "finance", requiresPermissions: ["finance.ar.read"] },
      { key: "ar-customers", label: "AR Customers", href: "/ar/customers", icon: "Users", moduleKey: "finance", requiresPermissions: ["finance.ar.read"] },
      { key: "ar-payments", label: "AR Payments", href: "/ar/payments", icon: "CreditCard", moduleKey: "finance", requiresPermissions: ["finance.ar.read"] },
      { key: "finance-ap", label: "Accounts Payable (AP)", href: "/finance/ap", icon: "ArrowUpCircle", moduleKey: "finance", requiresPermissions: ["finance.ap.read"] },
      { key: "ap-suppliers", label: "AP Suppliers", href: "/ap/suppliers", icon: "Building2", moduleKey: "finance", requiresPermissions: ["finance.ap.read"] },
      { key: "ap-bills", label: "AP Bills", href: "/ap/bills", icon: "Receipt", moduleKey: "finance", requiresPermissions: ["finance.ap.read"] },
      { key: "ap-payments", label: "AP Payments", href: "/ap/payments", icon: "CreditCard", moduleKey: "finance", requiresPermissions: ["finance.ap.read"] },
      { key: "ap-three-way-match", label: "3-way match", href: "/ap/three-way-match", icon: "GitCompare", moduleKey: "finance", requiresPermissions: ["finance.ap.read"] },
      { key: "finance-payments", label: "Payments & Receipts", href: "/finance/payments", icon: "CreditCard", moduleKey: "finance", requiresPermissions: ["finance.payments.read"] },
      { key: "finance-tax", label: "Tax / VAT", href: "/finance/tax", icon: "Receipt", moduleKey: "finance", requiresPermissions: ["finance.tax.read"] },
      { key: "finance-statements", label: "Financial Statements", href: "/finance/statements", icon: "BarChart3", moduleKey: "finance", requiresPermissions: ["finance.statements.read"], children: [
        { key: "finance-statements-pnl", label: "P&L", href: "/finance/statements/pnl", icon: "TrendingUp", moduleKey: "finance", requiresPermissions: ["finance.statements.read"] },
        { key: "finance-statements-balance-sheet", label: "Balance Sheet", href: "/finance/statements/balance-sheet", icon: "Scale", moduleKey: "finance", requiresPermissions: ["finance.statements.read"] },
        { key: "finance-statements-cash-flow", label: "Cash Flow", href: "/finance/statements/cash-flow", icon: "ArrowLeftRight", moduleKey: "finance", requiresPermissions: ["finance.statements.read"] },
      ]},
      { key: "finance-period-close", label: "Period Close", href: "/finance/period-close", icon: "Lock", moduleKey: "finance", requiresPermissions: ["finance.close.write"] },
      { key: "finance-budgets", label: "Budgets", href: "/finance/budgets", icon: "PiggyBank", moduleKey: "finance", requiresPermissions: ["finance.read"] },
      { key: "finance-ledger", label: "Ledger", href: "/finance/ledger", icon: "BookOpen", moduleKey: "finance", requiresPermissions: ["finance.gl.read"] },
      { key: "finance-audit", label: "Audit Log", href: "/finance/audit", icon: "FileSearch", moduleKey: "finance", requiresPermissions: ["finance.audit.read"] },
    ],
  },
  {
    key: "crm",
    label: "CRM",
    moduleKey: "crm",
    order: 16,
    items: [
      { key: "crm-accounts", label: "Accounts / Parties", href: "/crm/accounts", icon: "Building2", moduleKey: "crm", requiresPermissions: ["crm.accounts.read"] },
      { key: "crm-activities", label: "Activities / Notes", href: "/crm/activities", icon: "StickyNote", moduleKey: "crm", requiresPermissions: ["crm.activities.read"] },
      { key: "crm-deals", label: "Deals / Opportunities", href: "/crm/deals", icon: "TrendingUp", moduleKey: "crm", requiresPermissions: ["crm.deals.read"] },
      { key: "crm-tickets", label: "Support / Tickets", href: "/crm/tickets", icon: "Ticket", moduleKey: "crm", requiresPermissions: ["crm.tickets.read"] },
    ],
  },
  {
    key: "reports",
    label: "Reports",
    moduleKey: "reports",
    order: 17,
    items: [
      { key: "reports-library", label: "Report Library", href: "/reports", icon: "FileText", moduleKey: "reports", requiresPermissions: ["reports.read"] },
      { key: "reports-saved", label: "Saved Views", href: "/reports/saved", icon: "Bookmark", moduleKey: "reports", requiresPermissions: ["reports.read"] },
      { key: "reports-scheduled", label: "Scheduled Reports", href: "/reports/scheduled", icon: "Clock", moduleKey: "reports", requiresPermissions: ["reports.schedule.read"] },
      { key: "reports-exports", label: "Exports", href: "/reports/exports", icon: "Download", moduleKey: "reports", requiresPermissions: ["reports.export.read"] },
      { key: "reports-vat", label: "VAT Summary", href: "/reports/vat-summary", icon: "Receipt", moduleKey: "reports", requiresPermissions: ["reports.read"] },
      { key: "reports-wht", label: "WHT Summary", href: "/reports/wht-summary", icon: "Percent", moduleKey: "reports", requiresPermissions: ["reports.read"] },
    ],
  },
  {
    key: "analytics",
    label: "Analytics",
    moduleKey: "analytics",
    order: 18,
    items: [
      { key: "analytics-hub", label: "Analytics Studio", href: "/analytics", icon: "BarChart3", moduleKey: "analytics" },
      { key: "analytics-explore", label: "Explore", href: "/analytics/explore", icon: "Compass", moduleKey: "analytics" },
      { key: "analytics-insights", label: "Insights", href: "/analytics/insights", icon: "Lightbulb", moduleKey: "analytics" },
      { key: "analytics-anomalies", label: "Anomalies", href: "/analytics/anomalies", icon: "AlertTriangle", moduleKey: "analytics" },
      { key: "analytics-simulations", label: "Simulations", href: "/analytics/simulations", icon: "SlidersHorizontal", moduleKey: "analytics" },
      { key: "analytics-products", label: "Products", href: "/analytics/products", icon: "Package", moduleKey: "analytics" },
      { key: "analytics-pricing", label: "Pricing", href: "/analytics/pricing", icon: "TrendingUp", moduleKey: "analytics" },
      { key: "analytics-inventory", label: "Inventory", href: "/analytics/inventory", icon: "Warehouse", moduleKey: "analytics" },
      { key: "analytics-finance", label: "Finance", href: "/analytics/finance", icon: "Landmark", moduleKey: "analytics" },
      { key: "analytics-payroll", label: "Payroll", href: "/analytics/payroll", icon: "CreditCard", moduleKey: "analytics" },
      { key: "analytics-settings", label: "Analytics settings", href: "/analytics/settings", icon: "Settings", moduleKey: "analytics" },
    ],
  },
  {
    key: "automation",
    label: "Automation Center",
    moduleKey: "automation",
    order: 19,
    items: [
      { key: "automation-dashboard", label: "Automation Dashboard", href: "/automation", icon: "Zap", moduleKey: "automation", requiresPermissions: ["automation.read"] },
      { key: "automation-rules", label: "Rules Engine", href: "/automation/rules", icon: "Workflow", moduleKey: "automation", requiresPermissions: ["automation.rules.read"] },
      { key: "automation-alerts", label: "Alerts & Notifications", href: "/automation/alerts", icon: "Bell", moduleKey: "automation", requiresPermissions: ["automation.alerts.read"], badge: { type: "count", value: "3" } },
      { key: "automation-schedules", label: "Scheduled Jobs", href: "/automation/schedules", icon: "Calendar", moduleKey: "automation", requiresPermissions: ["automation.schedules.read"] },
      { key: "automation-workflows", label: "Approvals Workflows", href: "/automation/workflows", icon: "CheckCircle2", moduleKey: "automation", requiresPermissions: ["automation.workflows.read"] },
      { key: "automation-integrations", label: "Integrations", href: "/automation/integrations", icon: "Plug", moduleKey: "automation", requiresPermissions: ["automation.integrations.read"] },
      { key: "automation-ai-insights", label: "AI Insights", href: "/automation/ai-insights", icon: "Brain", moduleKey: "automation", requiresPermissions: ["automation.ai.read"], badge: { type: "text", value: "NEW" } },
      { key: "work-queue", label: "Work queue", href: "/work/queue", icon: "ListTodo", moduleKey: "automation", requiresPermissions: ["automation.read"] },
    ],
  },
  {
    key: "settings",
    label: "Settings",
    moduleKey: "settings",
    order: 20,
    items: [
      { key: "settings-org", label: "Organization Profile", href: "/settings/org", icon: "Building", moduleKey: "settings", requiresPermissions: ["settings.org.read"] },
      { key: "settings-entities", label: "Entities", href: "/settings/organization/entities", icon: "Building2", moduleKey: "settings", requiresPermissions: ["settings.org.read"] },
      { key: "settings-branches", label: "Branches", href: "/settings/branches", icon: "MapPin", moduleKey: "settings", termKey: "branch", requiresPermissions: ["settings.branches.read"] },
      { key: "settings-users-roles", label: "Users & Roles", href: "/settings/users-roles", icon: "Users", moduleKey: "settings", requiresPermissions: ["settings.users.read"] },
      { key: "settings-preferences", label: "Preferences", href: "/settings/preferences", icon: "Settings", moduleKey: "settings", requiresPermissions: ["settings.preferences.read"] },
      { key: "settings-sequences", label: "Numbering Sequences", href: "/settings/sequences", icon: "Hash", moduleKey: "settings", requiresPermissions: ["settings.sequences.read"] },
      { key: "settings-compliance", label: "Compliance", href: "/settings/compliance", icon: "ShieldCheck", moduleKey: "settings", requiresPermissions: ["settings.org.read"] },
      { key: "settings-notifications", label: "Notifications", href: "/settings/notifications", icon: "Bell", moduleKey: "settings", requiresPermissions: ["settings.org.read"] },
      { key: "settings-payroll", label: "Payroll", href: "/settings/payroll", icon: "CreditCard", moduleKey: "settings", requiresPermissions: ["settings.org.read"] },
      { key: "settings-audit-log", label: "Audit Log", href: "/settings/audit-log", icon: "FileSearch", moduleKey: "settings", requiresPermissions: ["settings.audit.read"] },
      { key: "settings-financial", label: "Financial", href: "/settings/financial/currencies", icon: "Wallet", moduleKey: "settings", requiresPermissions: ["settings.financial.read"], children: [
        { key: "settings-financial-currencies", label: "Currencies", href: "/settings/financial/currencies", icon: "Banknote", moduleKey: "settings", requiresPermissions: ["settings.financial.read"] },
        { key: "settings-financial-rates", label: "Exchange rates", href: "/settings/financial/exchange-rates", icon: "TrendingUp", moduleKey: "settings", requiresPermissions: ["settings.financial.read"] },
        { key: "settings-financial-coa", label: "Chart of Accounts", href: "/settings/financial/chart-of-accounts", icon: "ListTree", moduleKey: "settings", requiresPermissions: ["settings.financial.read"] },
        { key: "settings-financial-taxes", label: "Taxes", href: "/settings/financial/taxes", icon: "Receipt", moduleKey: "settings", requiresPermissions: ["settings.financial.read"] },
        { key: "settings-financial-fiscal", label: "Fiscal years", href: "/settings/financial/fiscal-years", icon: "Calendar", moduleKey: "settings", requiresPermissions: ["settings.financial.read"] },
      ]},
      { key: "settings-inventory", label: "Inventory", href: "/settings/inventory/costing", icon: "Package", moduleKey: "settings", requiresPermissions: ["settings.inventory.read"], children: [
        { key: "settings-inventory-costing", label: "Costing", href: "/settings/inventory/costing", icon: "Calculator", moduleKey: "settings", requiresPermissions: ["settings.inventory.read"] },
        { key: "settings-uom", label: "UOM catalog", href: "/settings/uom", icon: "Ruler", moduleKey: "settings", requiresPermissions: ["settings.inventory.read"] },
      ]},
      { key: "settings-products", label: "Products", href: "/settings/products/pricing-rules", icon: "Package", moduleKey: "settings", requiresPermissions: ["settings.inventory.read"], children: [
        { key: "settings-products-pricing-rules", label: "Pricing rules", href: "/settings/products/pricing-rules", icon: "Calculator", moduleKey: "settings", requiresPermissions: ["settings.inventory.read"] },
      ]},
      { key: "settings-tax", label: "Tax (Kenya)", href: "/settings/tax/kenya", icon: "Receipt", moduleKey: "settings", requiresPermissions: ["settings.financial.read"], children: [
        { key: "settings-tax-kenya", label: "Kenya profile", href: "/settings/tax/kenya", icon: "Globe", moduleKey: "settings", requiresPermissions: ["settings.financial.read"] },
        { key: "settings-tax-vat", label: "VAT", href: "/settings/tax/vat", icon: "Receipt", moduleKey: "settings", requiresPermissions: ["settings.financial.read"] },
        { key: "settings-tax-withholding", label: "Withholding", href: "/settings/tax/withholding", icon: "Percent", moduleKey: "settings", requiresPermissions: ["settings.financial.read"] },
        { key: "settings-tax-mappings", label: "Tax mappings", href: "/settings/tax/tax-mappings", icon: "Link", moduleKey: "settings", requiresPermissions: ["settings.financial.read"] },
      ]},
      { key: "settings-customizer", label: "Customizer (Enterprise)", href: "/settings/customizer", icon: "Sliders", moduleKey: "settings", requiresPermissions: ["settings.customizer.read"], children: [
        { key: "settings-customizer-modules", label: "Modules", href: "/settings/customizer/modules", icon: "Grid", moduleKey: "settings", requiresPermissions: ["settings.customizer.read"] },
        { key: "settings-customizer-fields", label: "Custom Fields", href: "/settings/customizer/fields", icon: "FileText", moduleKey: "settings", requiresPermissions: ["settings.customizer.read"] },
        { key: "settings-customizer-workflows", label: "Workflows", href: "/settings/customizer/workflows", icon: "Workflow", moduleKey: "settings", requiresPermissions: ["settings.customizer.read"] },
        { key: "settings-customizer-dashboards", label: "Dashboards", href: "/settings/customizer/dashboards", icon: "LayoutDashboard", moduleKey: "settings", requiresPermissions: ["settings.customizer.read"] },
      ]},
    ],
  },
];
