import type { IndustryTemplateDefinition } from "./types";

export const INDUSTRY_TEMPLATES_REGISTRY: Record<string, IndustryTemplateDefinition> = {
  "fmcg-manufacturer": {
    id: "fmcg-manufacturer",
    name: "FMCG Manufacturer",
    description: "Raw materials → production → finished goods. Batch/expiry, BOM, work orders, costing.",
    orgType: "MANUFACTURER",
    icon: "Factory",
    enabledModules: [
      "dashboard",
      "masters",
      "inventory",
      "sales",
      "purchasing",
      "pricing",
      "finance",
      "manufacturing",
      "crm",
      "projects",
      "reports",
      "automation",
      "analytics",
      "settings",
      "docs",
    ],
    defaultNav: [
      "core",
      "docs",
      "masters",
      "inventory",
      "warehouse",
      "sales",
      "purchasing",
      "pricing",
      "manufacturing",
      "finance",
      "treasury",
      "assets",
      "projects",
      "payroll",
      "intercompany",
      "crm",
      "reports",
      "analytics",
      "automation",
      "settings",
    ],
    featureFlags: {
      batchExpiry: true,
      approvals: true,
      costing: true,
      bomMrpWorkOrders: true,
      multiWarehouse: true,
      workOrders: true,
    },
    terminology: {
      customer: "Customer",
      supplier: "Supplier",
      product: "Finished Good / SKU",
      warehouse: "Warehouse",
      branch: "Plant / Branch",
      salesOrder: "Sales Order",
      purchaseOrder: "Purchase Order",
      goodsReceipt: "Goods Receipt (GRN)",
      invoice: "Invoice",
      journalEntry: "Journal Entry",
      workOrder: "Work Order",
      bom: "Bill of Materials",
    },
    defaultKPIs: [
      { kpiId: "production-output", label: "Production Output", order: 1 },
      { kpiId: "yield-pct", label: "Yield %", order: 2 },
      { kpiId: "stockouts", label: "Stockouts", order: 3 },
      { kpiId: "stock-value", label: "Stock Value", order: 4 },
    ],
    defaultRoleDashboards: [
      { roleId: "admin", widgetIds: ["production-overview", "inventory-levels", "pending-work-orders", "recent-grn"] },
      { roleId: "production", widgetIds: ["work-orders-due", "bom-usage", "wip-value"] },
    ],
    onboardingDefaults: {
      currency: "KES",
      taxMode: "inclusive",
      fiscalYearStartMonth: 1,
      warehouseMode: "multi",
      defaultCountry: "KE",
      defaultTimezone: "Africa/Nairobi",
    },
  },

  "fmcg-distributor": {
    id: "fmcg-distributor",
    name: "FMCG Distributor",
    description: "Stock in → allocation → deliveries → collections. Routes, POD, batch/expiry.",
    orgType: "DISTRIBUTOR",
    icon: "Truck",
    enabledModules: [
      "dashboard",
      "masters",
      "inventory",
      "sales",
      "purchasing",
      "pricing",
      "finance",
      "distribution",
      "crm",
      "projects",
      "reports",
      "automation",
      "analytics",
      "settings",
      "docs",
    ],
    defaultNav: [
      "core",
      "docs",
      "masters",
      "inventory",
      "warehouse",
      "sales",
      "purchasing",
      "pricing",
      "distribution",
      "finance",
      "treasury",
      "assets",
      "projects",
      "payroll",
      "intercompany",
      "crm",
      "reports",
      "analytics",
      "automation",
      "settings",
    ],
    featureFlags: {
      batchExpiry: true,
      approvals: true,
      multiWarehouse: true,
      routesPromotionsPos: false,
      deliveries: true,
      collections: true,
    },
    terminology: {
      customer: "Outlet / Customer",
      supplier: "Supplier",
      product: "Product",
      warehouse: "Warehouse",
      branch: "Depot / Branch",
      outlet: "Outlet",
      salesOrder: "Order",
      purchaseOrder: "Purchase Order",
      goodsReceipt: "Goods Receipt (GRN)",
      invoice: "Invoice",
      journalEntry: "Journal Entry",
      route: "Route",
      delivery: "Delivery",
      collection: "Collection",
    },
    defaultKPIs: [
      { kpiId: "otif", label: "OTIF", order: 1 },
      { kpiId: "near-expiry", label: "Near Expiry", order: 2 },
      { kpiId: "collections", label: "Collections", order: 3 },
      { kpiId: "fill-rate", label: "Fill Rate", order: 4 },
    ],
    defaultRoleDashboards: [
      { roleId: "admin", widgetIds: ["stock-levels", "pending-deliveries", "collections-overview", "recent-orders"] },
      { roleId: "sales", widgetIds: ["route-coverage", "outlet-visits", "collections-due"] },
    ],
    onboardingDefaults: {
      currency: "KES",
      taxMode: "inclusive",
      fiscalYearStartMonth: 1,
      warehouseMode: "multi",
      defaultCountry: "KE",
      defaultTimezone: "Africa/Nairobi",
    },
  },

  "retail-multi-store": {
    id: "retail-multi-store",
    name: "Retail Multi-Store",
    description: "Stores, replenishment, promotions, POS. Multi-outlet and store performance.",
    orgType: "RETAIL",
    icon: "Store",
    enabledModules: [
      "dashboard",
      "masters",
      "inventory",
      "sales",
      "purchasing",
      "pricing",
      "finance",
      "retail",
      "crm",
      "projects",
      "reports",
      "automation",
      "analytics",
      "settings",
      "docs",
    ],
    defaultNav: [
      "core",
      "docs",
      "masters",
      "inventory",
      "warehouse",
      "sales",
      "purchasing",
      "pricing",
      "retail",
      "finance",
      "treasury",
      "assets",
      "projects",
      "payroll",
      "intercompany",
      "crm",
      "reports",
      "analytics",
      "automation",
      "settings",
    ],
    featureFlags: {
      approvals: true,
      multiWarehouse: true,
      routesPromotionsPos: true,
      replenishment: true,
      promotions: true,
      storePerformance: true,
    },
    terminology: {
      customer: "Customer",
      supplier: "Supplier",
      product: "SKU",
      warehouse: "Store / Warehouse",
      branch: "Store",
      outlet: "Outlet",
      salesOrder: "Sales Order",
      purchaseOrder: "Purchase Order",
      goodsReceipt: "Goods In",
      invoice: "Invoice",
      journalEntry: "Journal Entry",
      replenishment: "Replenishment",
      promotion: "Promotion",
      store: "Store",
    },
    defaultKPIs: [
      { kpiId: "sales-mtd", label: "Sales MTD", order: 1 },
      { kpiId: "stock-levels", label: "Stock Levels", order: 2 },
      { kpiId: "reorder-suggestions", label: "Reorder Suggestions", order: 3 },
      { kpiId: "store-performance", label: "Store Performance", order: 4 },
    ],
    defaultRoleDashboards: [
      { roleId: "admin", widgetIds: ["sales-by-store", "replenishment-due", "promotions-active", "stock-levels"] },
      { roleId: "store-manager", widgetIds: ["store-sales", "stock-levels", "replenishment-suggestions"] },
    ],
    onboardingDefaults: {
      currency: "KES",
      taxMode: "inclusive",
      fiscalYearStartMonth: 1,
      warehouseMode: "multi",
      defaultCountry: "KE",
      defaultTimezone: "Africa/Nairobi",
    },
  },
};

export function getTemplateById(templateId: string): IndustryTemplateDefinition | null {
  return INDUSTRY_TEMPLATES_REGISTRY[templateId] ?? null;
}

export function getTemplatesByOrgType(orgType: "MANUFACTURER" | "DISTRIBUTOR" | "RETAIL"): IndustryTemplateDefinition[] {
  return Object.values(INDUSTRY_TEMPLATES_REGISTRY).filter((t) => t.orgType === orgType);
}

export function getAllTemplates(): IndustryTemplateDefinition[] {
  return Object.values(INDUSTRY_TEMPLATES_REGISTRY);
}

export const MODULE_LABELS: Record<string, string> = {
  dashboard: "Dashboard",
  masters: "Masters",
  inventory: "Inventory",
  sales: "Sales",
  purchasing: "Purchasing",
  finance: "Finance",
  manufacturing: "Manufacturing",
  distribution: "Distribution",
  retail: "Retail",
  crm: "CRM",
  reports: "Reports",
  automation: "Automation",
  settings: "Settings",
  docs: "Document Center",
};
